giantswarm/prometheus-meta-operator

- service/controller/resource/prometheus/delete.go
Closes https://github.com/giantswarm/giantswarm/issues/8152
> Ignore not found when deleting prometheus

- service/controller/resource/prometheus/resource.go
Closes https://github.com/giantswarm/giantswarm/issues/8153
Closes https://github.com/giantswarm/giantswarm/issues/8148
> Refactors prometheus CR creation

- flag/service/prometheus/prometheus.go
- flag/service/service.go
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- main.go
- service/controller/controller.go
- service/controller/controller_resource_set.go
- service/controller/resource/ingress/create.go
- service/controller/resource/ingress/delete.go
- service/controller/resource/ingress/error.go
- service/controller/resource/ingress/resource.go
- service/service.go
Closes https://github.com/giantswarm/giantswarm/issues/8118
> Adds ingress resource

- service/controller/controller_resource_set.go
- service/controller/resource/prometheus/resource.go
- service/controller/resource/servicemonitor/create.go
- service/controller/resource/servicemonitor/delete.go
- service/controller/resource/servicemonitor/error.go
- service/controller/resource/servicemonitor/resource.go
- service/controller/resource/servicemonitor/services.go
- service/key/key.go
Closes https://github.com/giantswarm/giantswarm/issues/8119
> Implements service monitor resource

- helm/prometheus-meta-operator/templates/rbac.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8119
> Adds servicemonitors to rbac

- service/controller/resource/servicemonitor/services.go
Towards https://github.com/giantswarm/giantswarm/issues/8119
> Use InsecureSkipVerify for scraping apiserver

- service/controller/resource/prometheus/resource.go
> Alphabetises prometheus spec

- .circleci/config.yml
- flag/flag.go
- helm/prometheus-meta-operator/Chart.yaml
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/deployment.yaml
- helm/prometheus-meta-operator/templates/pull-secret.yaml
- helm/prometheus-meta-operator/values.yaml
- main.go
- service/controller/controller.go
- service/controller/resource/alert/resource.go
- service/controller/resource/alert/rules/apiserver.go
- service/controller/resource/certificates/resource.go
- service/controller/resource/frontend/resource.go
- service/controller/resource/ingress/resource.go
- service/controller/resource/namespace/resource.go
- service/controller/resource/prometheus/resource.go
- service/controller/resource/service/resource.go
- service/controller/resource/servicemonitor/services.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/10899
* update ci
* push docker image to aliyun (china)
* push to aws,azure,and kvm app collections
* update chart
* configure docker image for china
> deploy to all installations

- CHANGELOG.md
- SECURITY.md
- pkg/project/project.go
Towards: https://github.com/giantswarm/giantswarm/issues/10899
> release v0.1.0

- CHANGELOG.md
- pkg/project/project.go
Towards: https://github.com/giantswarm/giantswarm/issues/10899
> release v0.1.1

- CHANGELOG.md
- pkg/project/project.go
Towards: https://github.com/giantswarm/giantswarm/issues/10898
> prepare 0.2.0-dev

- service/controller/resource/frontend/create.go
Towards: https://github.com/giantswarm/giantswarm/issues/11479
> delete frontend resource

- service/controller/resource/ingress/create.go
Towards: https://github.com/giantswarm/giantswarm/issues/11479
> delete ingress resource

- service/controller/resource/servicemonitor/create.go
- service/controller/resource/servicemonitor/resource.go
- service/controller/resource/servicemonitor/service/apiserver.go
Towards: https://github.com/giantswarm/giantswarm/issues/11392
* moved apiserver servicemonitor to servicemonitor/service/apiserver.go
* improved reconciliation
> servicemonitor improve reconciliation

- CHANGELOG.md
> Fix links in CHANGELOG

- CHANGELOG.md
- pkg/project/project.go
Towards https://github.com/giantswarm/giantswarm/issues/11829
> Releases v0.2.1

- .circleci/config.yml
- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/12001
Details: https://github.com/giantswarm/giantswarm/issues/12001#issuecomment-654757218
> set prometheus request and limits to cpu: 100m, memory: 100Mi

- service/controller/resource/prometheus/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/11724
> set prometheus memory limit to 200Mi

- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/12251.
> Add ChangeLog entry

- CHANGELOG.md
- flag/service/prometheus/prometheus.go
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- main.go
- service/controller/clusterapi/controller.go
- service/controller/legacy/controller.go
- service/controller/resource/prometheus/resource.go
- service/controller/resource/resource.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/11720
Tested on gauss
> Move PMOs persistent storage to PVC

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/12509
Tested on ghost
> Remove TC Prometheus limits

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
Towards: giantswarm/giantswarm#11724
> add kubelet target

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
Towards: giantswarm/giantswarm#11724
```
$ curl -s http://127.0.0.1:10251/metrics|grep scheduler_volume_scheduling_duration_seconds_sum
scheduler_volume_scheduling_duration_seconds_sum{operation="assume"} 0.00023070100000000004
```
> add kube-scheduler target

- CHANGELOG.md
- go.mod
Reverts giantswarm/prometheus-meta-operator#105
> Revert "Upgrade to go 1.15"

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/11723
> gatekeeper target

- Documentation/targets.md
Towards https://github.com/giantswarm/giantswarm/issues/12925
> Update list of targets

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
> Add cert operator target

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/11723
Tested ...
on `gauss`
on `gorilla`
> add managed-app/crsync target

- service/key/key.go
Towards: https://github.com/giantswarm/giantswarm/issues/13005
> Fix API URL computation for Cluster objects

- pkg/unittest/input/case-1-awsconfig.golden
- pkg/unittest/input/case-2-azureconfig.golden
- pkg/unittest/input/case-3-kvmconfig.golden
- pkg/unittest/input/case-4-control-plane.golden
- service/controller/resource/namespace/test/case-1-awsconfig.golden
- service/controller/resource/namespace/test/case-2-azureconfig.golden
- service/controller/resource/namespace/test/case-3-kvmconfig.golden
- service/controller/resource/namespace/test/case-4-control-plane.golden
Towards: https://github.com/giantswarm/giantswarm/issues/12981
> add more unit test cases

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
> Add kvm targets and coredns

- helm/prometheus-meta-operator/templates/deployment.yaml
Closes https://github.com/giantswarm/giantswarm/issues/13295
> Adds revision history limit

- CHANGELOG.md
- files/templates/additional-scrape-configs.template.yaml
- service/controller/resource/prometheus/resource.go
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/13223 and https://github.com/giantswarm/giantswarm/issues/13222
> Add scraping of prometheuses

- files/templates/additional-scrape-configs.template.yaml
- service/controller/resource/alert/rules/labellingschema.go
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/servicemonitor/service/cluster_autoscaler.go
- service/controller/resource/servicemonitor/service/nginx-ingress-controller.go
Towards https://github.com/giantswarm/giantswarm/issues/10904
> Fix some missing labels on metrics

- flag/service/prometheus/prometheus.go
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- main.go
- service/controller/clusterapi/controller.go
- service/controller/control-plane/controller.go
- service/controller/control-plane/resource.go
- service/controller/legacy/controller.go
- service/controller/resource/prometheus/resource.go
- service/controller/resource/resource.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/11524
> set external url

- CHANGELOG.md
- flag/service/security/security.go
- flag/service/service.go
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/templates/ingress-oauth.yaml
- helm/prometheus-meta-operator/templates/prometheus-tls-secret.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- helm/prometheus-meta-operator/values.yaml
- main.go
- service/controller/clusterapi/controller.go
- service/controller/control-plane/controller.go
- service/controller/control-plane/resource.go
- service/controller/legacy/controller.go
- service/controller/resource/generic/create.go
- service/controller/resource/ingress/client.go
- service/controller/resource/ingress/resource.go
- service/controller/resource/ingress/resource_test.go
- service/controller/resource/ingress/test/case-0-cluster-api.golden
- service/controller/resource/ingress/test/case-1-awsconfig.golden
- service/controller/resource/ingress/test/case-2-azureconfig.golden
- service/controller/resource/ingress/test/case-3-kvmconfig.golden
- service/controller/resource/ingress/test/case-4-control-plane.golden
- service/controller/resource/ingress/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/prometheus/resource.go
- service/controller/resource/resource.go
- service/key/key.go
- service/service.go
Towards https://github.com/giantswarm/giantswarm/issues/13366
This still needs to be tested though
> Add prometheus ingress

- CHANGELOG.md
- service/controller/resource/alert/rules/heartbeat.go
- service/controller/resource/heartbeat/resource.go
- service/key/key.go
Towards: https://github.com/giantswarm/giantswarm/issues/13302
> add key values for heartbeats

- service/key/key.go
Towards https://github.com/giantswarm/prometheus-meta-operator/pull/184
> Little refactoring

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14076
> increase memory request to 5Gi

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14244
Before
After
> fix prometheus target

- files/templates/rules/alerts/prometheus.yml
- service/controller/resource/alert/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/14244
> add PrometheusCantCommunicateWithTenantAPI

- files/templates/rules/recording/cortex.yml
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/14348
> Fix memory usage aggregation

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14389
> set resource limits

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14389
> set cpu requests/limits to 0.5

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14389
> set cpu requests/limits to 0.25

- CHANGELOG.md
- pkg/project/project.go
Towards: https://github.com/giantswarm/giantswarm/issues/14389
> Release v1.10.2

- CHANGELOG.md
- service/controller/resource/heartbeat/create.go
- service/controller/resource/heartbeat/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/14556
> Fix heartbeat ping

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14635
> Set affinity to required instead of prefer

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus.rules.yml
Closes https://github.com/giantswarm/giantswarm/issues/14483
> Ignores promxy in PrometheusCantCommunicate alert

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/14661
> Set prometheus default resource

- service/controller/resource/verticalpodautoscaler/error.go
- service/controller/resource/verticalpodautoscaler/resource.go
I reckoned fixing it would be quicker / less annoying that commenting on a merged PR, so **bam!**
> Fixes convertion typo

- CHANGELOG.md
- files/templates/rules/alerts/prometheus-meta-operator.yml
Towards: giantswarm/giantswarm#14998
> improve heartbeat

- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.yml
Towards: giantswarm/giantswarm#14998
> improve heartbeat (without confusion)

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/verticalpodautoscaler/resource.go
- service/controller/resource/verticalpodautoscaler/test/case-0-cluster-api.golden
- service/controller/resource/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/15235
> Set prometheus minimal memory in vpa

- CHANGELOG.md
- service/controller/resource/heartbeat/delete.go
Towards https://github.com/giantswarm/giantswarm/issues/15362
> Trigger one final heartbeat before deleting it to clean up opened heartbeat alerts

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/alertmanager.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15131 and https://github.com/giantswarm/g8s-prometheus/pull/1230
> Updates AlertManagerNotificationsFailing alerts

- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
- helm/prometheus-meta-operator/templates/recording-rules/helm-operations.rules.yml
- helm/prometheus-meta-operator/templates/recording-rules/service-levels.rules.yml
Signed-off-by: QuentinBisson <quentin@giantswarm.io>
> Refresh recording rules

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/inhibit.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/inhibit.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/microendpoint.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/up.rules.yml
This PR fixes some rules to only be present when they should (control_plane and provider split)
> fix-some-rules-per-provider

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Fixing the aggregation:kubernetes:up metrics in cortex
> Fix missing app label on some target

- .github/pull_request_template.md
So that we can double-check that we have followed the couple of
guidelines that make the change complete and make reviewer's life a
little bit simpler.
> Add pull request template ❤

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
Fix invalid prometheus memory usage recording rule
Towards #15508
I have:
> fix(15508): Fix invalid prometheus memory usage recording rule

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/app.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/cert-manager.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/certificate.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/certificate.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/chart.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/configmap.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/configmap.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/configmap.workload-cluster.rules copy.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/crsync.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/deployment.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/deployment.workload-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/elasticsearch.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/external-dns.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/helm.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/ingress-controller.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/inhibit.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/inhibit.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/managed-apps-basic-sli.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/managed-logging.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/microendpoint.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/operatorkit.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/secret.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/tiller.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/tiller.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/tiller.workload-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/up.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/up.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/recording-rules/service-levels.rules.yml
Towards **https://github.com/giantswarm/giantswarm/issues/15513 Move Managed Apps alerts to PMO**
This PR adds batman alerts to PMO
I have:
> Add batman alerts

- go.mod
- pkg/unittest/unittest.go
- service/controller/legacy/controller.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/15588
I have:
> Update apiextensions to v3.17.0

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/alertmanager.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/daemonset.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/deployment.management-cluster.rules.yml
Same as https://github.com/giantswarm/g8s-prometheus/pull/1251
I have:
> Drop axolotl in rules

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/cloud.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/cluster-autoscaler.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/etcd.workload-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/network.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/timesync.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/up.workload-cluster.rules.yml
> fix: helm template not working for empty prometheus rules on aws and kvm

- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
Remove uncessary label_replace that were needed when we were having exported_cluster_id
> Remove unecessary label_replace

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15656
I have:
> Fix AzureClusterCreationFailed alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/deployment.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/etcd.workload-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/kvm.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/kvm.workload-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/microendpoint.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/network.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/operatorkit.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/timesync.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/up.workload-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15605
I have:
> Add Rocket rules

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/cluster-service.rules.yml
> Add TestClusterTooOld alert

- hack/sync-heartbeat-silences.sh
Towards: https://github.com/giantswarm/giantswarm/issues/15680
Adding a hacky script to help us syncrhonize heartbeat and silences.
I have:
> add hack/sync-heartbeat-silences.sh script

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/resource.go
Discover WC etcd through their ingress to avoid issues when they are in private networks
I have:
> Etcd scrape through api proxy

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- flag/service/prometheus/prometheus.go
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- main.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/scrapeconfigs/resource.go
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/service.go
Add missing scrape targets https://github.com/giantswarm/giantswarm/issues/15840
I have:
> Add missing targets

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/10906
I have:
> Add alert for missing prometheus

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
> Send samples per second to cortex

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Set the web page title to be able to know to which prometheus I am talking to
Closes #https://github.com/giantswarm/giantswarm/issues/13368
I have:
> Set web page title

- CHANGELOG.md
- service/controller/resource/verticalpodautoscaler/create.go
- service/controller/resource/verticalpodautoscaler/resource.go
Fix VPA craziness by maintaining the status after a pmo restart
Closes https://github.com/giantswarm/giantswarm/issues/15930
Closes https://github.com/giantswarm/giantswarm/issues/15924
Closes https://github.com/giantswarm/giantswarm/issues/15927
I have:
> Fix VPA craziness

- CHANGELOG.md
- service/controller/resource/certificates/resource.go
- service/controller/resource/resource.go
- service/key/key.go
> Support both CAPI certs and legacy certs

- helm/prometheus-meta-operator/Chart.yaml
Towards giantswarm/giantswarm#14846
> Add team annotation to Chart.yaml

- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
> disable-WorkloadClusterCriticalPodNotRunningAWS

- service/controller/resource/certificates/create.go
- service/controller/resource/certificates/delete.go
- service/controller/resource/generic/create.go
- service/controller/resource/generic/delete.go
- service/controller/resource/heartbeat/create.go
- service/controller/resource/heartbeat/delete.go
- service/controller/resource/heartbeatrouting/create.go
- service/controller/resource/heartbeatrouting/delete.go
- service/controller/resource/promxy/create.go
- service/controller/resource/promxy/delete.go
- service/controller/resource/rbac/create.go
- service/controller/resource/rbac/delete.go
- service/controller/resource/verticalpodautoscaler/create.go
- service/controller/resource/verticalpodautoscaler/delete.go
- service/controller/resource/volumeresizehack/create.go
- service/controller/resource/wrapper/monitoringdisabledresource/resource.go
> Change logging api calls

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/ingress-oauth.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- service/controller/resource/ingress/client.go
- service/controller/resource/ingress/resource.go
> refacto: Upgrade ingress version to networking.k8s.io/v1beta1

- .circleci/config.yml
- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/etcd.workload-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/network.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/operatorkit.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/timesync.rules.yml
- service/service.go
Replacing https://github.com/giantswarm/prometheus-meta-operator/pull/413
I have:
> feat: Add support to monitor vmware clusters

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.rules.yml
> Fix Matching number of Prometheus alert

- CHANGELOG.md
- service/controller/resource/verticalpodautoscaler/resource.go
- service/controller/resource/verticalpodautoscaler/test/case-0-cluster-api.golden
- service/controller/resource/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
> Set min cpu resource in vpa

- .circleci/config.yml
- CHANGELOG.md
> Update architect to 2.4.2

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
We (UX hive) see a need for aggregated dex activity and status data, to analyse SSO usage as well as have a signal on errors.
Towards https://github.com/giantswarm/giantswarm/issues/16445
I have:
> Add recording rules for dex activity

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/disk.management-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15871
Towards https://github.com/giantswarm/giantswarm/issues/16537
I have:
TODO: 
Clean up PVC silences
> feat(#15871): Alert when prometheus storage is over 90%

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
> Do not monitor docker for CAPI clusters

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/apiserver.workload-cluster.rules.yml
I have:
- [ x ] Described why this change is being introduced
- [ x ] Separated out refactoring/reformatting in a dedicated PR
- [ x ] Updated changelog in `CHANGELOG.md`
Related PM: https://github.com/giantswarm/giantswarm/issues/15938
> Increase duration for WorkloadClusterWebhookDurationExceedsTimeout alert

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
> Add Missing Workload App labels

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus.rules.yml
This alert will be used to detect communication issues between cortex and prometheus
I have:
> Page when prometheus cannot send samples to cortex

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- helm/prometheus-meta-operator/templates/prometheus-rules/disk.management-cluster.rules.yml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/16537
Closes https://github.com/giantswarm/giantswarm/issues/15871
I have:
> Fix(16537) Prometheus Storage alert

- helm/prometheus-meta-operator/templates/prometheus-rules/disk.management-cluster.rules.yml
> Add missing group left

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/15832
I have:
> Page Firecracker in working hours for restarting containers

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.management-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15834
I have:
> page for failed cluster transitions

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/recording-rules/kubernetes-mixins.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/13725
I have:
> Add recording rules for kube-mixins

- helm/prometheus-meta-operator/templates/prometheus-rules/up.all.rules.yml
> Fix app name in ksm missing alert

- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/16446
I have:
> Tune remote write for better throughput

- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
> adjust-container-restarting-too-often-firecracker

- .nancy-ignore
> ignore jwt issue nancy

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15615 https://github.com/giantswarm/giantswarm/issues/15618
I have:
> remove unused notify alerts for firecracker

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Towards: https://github.com/giantswarm/giantswarm/issues/16803
> Raise CPU limit to 150%

- helm/prometheus-meta-operator/templates/prometheus-rules/managed-apps-basic-sli.rules.yml
> Fix typo in alert description

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
I have:
- [ x] Updated changelog in `CHANGELOG.md`
> Add metric relabel config for KMS

- CHANGELOG.md
- main.go
- service/controller/resource/alertmanagerconfig/resource.go
- service/controller/resource/alertmanagerconfig/test/case-0-cluster-api.golden
- service/controller/resource/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/prometheus/resource_test.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Upgrade prometheus to 2.27.1
I have:
> Bump prometheus default value to 2.27.1

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/network.all.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/node.workload_cluster.rules.yml
towards https://github.com/giantswarm/giantswarm/issues/16843
alert if there are too many node terminations per period to time, this alert should not page unless there something very wrong
> alert-too-many-autotermination

- service/controller/clusterapi/controller.go
- service/controller/legacy/controller.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/prometheus/resource.go
- service/controller/resource/resource.go
- service/service.go
> Add Proxy URL to remote write

- CHANGELOG.md
> Fix typo in changelog header

- CHANGELOG.md
- flag/service/prometheus/prometheus.go
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/values.yaml
- main.go
- service/controller/clusterapi/controller.go
- service/controller/legacy/controller.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/resource_test.go
- service/controller/resource/monitoring/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/resource.go
This changes adds the possibility to override the prometheus log level to investigate issues more easily
I have:
> Add prometheus log level

- helm/prometheus-meta-operator/ci/default-values.yaml
- service/controller/managementcluster/resource.go
- service/controller/resource/monitoring/ingress/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/resource_test.go
- service/controller/resource/monitoring/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/rbac/doc.go
- service/controller/resource/resource.go
- service/key/key.go
This changes introduces refactoring to preparing for the addition of alertmanager and fixes some leftovers
I have:
> Clean up and rename a few internal variables

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/network.all.rules.yml
I have:
related to https://github.com/giantswarm/giantswarm/issues/17439
> Change severity to notify for HighNumberOfAllocatedSockets alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/service-level.rules.yml
- helm/prometheus-meta-operator/templates/recording-rules/service-levels.rules.yml
> Extract SLO targets for different services

- flag/service/alertmanager/alertmanager.go
- flag/service/grafana/grafana.go
- flag/service/service.go
- flag/service/slack/slack.go
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/values.yaml
- main.go
This PR adds the Alertmanager, Grafana and slack messages that are required for the new alertmanager code base
I have:
> Add new flags for alertmanager

- CHANGELOG.md
- flag/service/alertmanager/alertmanager.go
- helm/prometheus-meta-operator/templates/alertmanager-ingress.yaml
- helm/prometheus-meta-operator/templates/alertmanager-tls-secret.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/templates/ingress-oauth.yaml
- main.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanagerconfigsecret/resource.go
- service/service.go
> Add Alertmanager TLS ingress

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager-ingress.yaml
> Fix Ingress service name

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/certificate.management-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/17579. More explicit explanation in [this comment](https://github.com/giantswarm/giantswarm/issues/17579#issuecomment-862027504).
I have:
> Merge MC certificate rules into one PrometheusRule CR

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/app.rules.yml
I have added `AppPendingUpdate` alert to notify team-batman when app CRs are not updated to the version we specified in CRs with keeping `deployed` status.
> Add pending update alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/apiserver.management-cluster.rules.yml
> Increased webhook timeout to 15m

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/azure.management-cluster.rules.yml
> Fix typo in Azure cluster rules.

- .circleci/config.yml
> Downgrade architect orb to avoid argo issue

- .circleci/config.yml
> allow pushing image to aliyun on PR with approval

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
Copying change from https://github.com/giantswarm/g8s-prometheus/pull/1306
I have:
> Add service to SLO alert

- CHANGELOG.md
- main.go
- service/controller/resource/monitoring/prometheus/resource_test.go
- service/controller/resource/monitoring/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
Upgrading prometheus to the latest version
I have:
> Update prom to 2.28.1

- .circleci/config.yml
Fixes an issue where our docker image was not pushed to docker.io
> push to docker.io

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-0-cluster-api.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
> Remove cloud limit alerts from customer accounts

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
This PR fixes an issue where `app` label is now missing due to wrong relabeling.
> fix app label relabeling

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-0-cluster-api.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
See: https://github.com/giantswarm/prometheus-rules/pull/185#discussion_r771260558
I have:
> Renamed `cancel_if_has_no_workers` inhibition

- .circleci/config.yml
- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
> Add support for OpenStack

- files/templates/scrapeconfigs/_node_exporter_namespace.yaml
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/roadmap/issues/725
> Scrape node-exporter trough apiserver proxy

- service/controller/resource/monitoring/scrapeconfigs/resource_test.go
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/20918
The tests are copied from kvm and edited manually. No changelog is intentional. There are no semantic changes.
> Add tests for openstack

- CODEOWNERS
Ask Team Atlas review for every PR.
> make Team Atlas full codeowners

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/ingress-oauth.yaml
> Add alertmanager ingress oauth

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
> Clean up alertmanager template

- flag/service/alertmanager/alertmanager.go
- main.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/service.go
Adding flags in preparation for some follow up prs
I have:
> Add missing alertmanager flags

- CHANGELOG.md
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanager/resource.go
- service/controller/resource/alerting/ingress/v1/client.go
- service/controller/resource/alerting/ingress/v1/resource.go
- service/controller/resource/alerting/ingress/v1/resource_test.go
- service/controller/resource/alerting/ingress/v1/test/case-1-awsconfig.golden
- service/controller/resource/alerting/ingress/v1/test/case-2-azureconfig.golden
- service/controller/resource/alerting/ingress/v1/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/ingress/v1/test/case-4-control-plane.golden
- service/controller/resource/alerting/ingress/v1/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/alerting/ingress/v1beta1/client.go
- service/controller/resource/alerting/ingress/v1beta1/resource.go
- service/controller/resource/alerting/ingress/v1beta1/resource_test.go
- service/controller/resource/alerting/ingress/v1beta1/test/case-1-awsconfig.golden
- service/controller/resource/alerting/ingress/v1beta1/test/case-2-azureconfig.golden
- service/controller/resource/alerting/ingress/v1beta1/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/ingress/v1beta1/test/case-4-control-plane.golden
- service/controller/resource/alerting/ingress/v1beta1/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/ingress/v1/resource.go
- service/controller/resource/monitoring/ingress/v1beta1/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/ingress/v1beta1/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/ingress/v1beta1/test/case-4-control-plane.golden
- service/controller/resource/monitoring/ingress/v1beta1/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
> Add alertmanager ingress resources

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager-ingress.yaml
Towards https://github.com/giantswarm/roadmap/issues/937
I have:
> Add ingress resource for alertmanager

- service/key/key.go
Address of late comments on https://github.com/giantswarm/prometheus-meta-operator/pull/882
I have:
> Improve CAPI cluster detection.

- CHANGELOG.md
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/key/key.go
Fix CAPI Management Cluster detection
Tested on legacy MCs and on gubble. Seems to work fine
I have:
> Mc capi detection

- CHANGELOG.md
- service/key/key.go
towards https://github.com/giantswarm/giantswarm/issues/22106
I have:
> add support for VCD provider and order providers alphabetically

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/22500
Tested on ghost MC, waiting for 3.7.0 to be released before testing on a workload cluster.
I have:
> Fix api server discovery

- CHANGELOG.md
- pkg/unittest/error.go
- service/controller/resource/prometheusremotewrite/resource_test.go
issue: https://github.com/giantswarm/roadmap/issues/1140
Adding unit tests for remote write functionality. 
I have:
> Add test for Remotewrite feature

- CHANGELOG.md
- service/key/key.go
> rename vcd to cloud-director

- pkg/project/project.go
> Bump version in project.go

- .nancy-ignore
- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager-psp.yaml
- helm/prometheus-meta-operator/templates/alertmanager-rbac.yaml
- helm/prometheus-meta-operator/templates/prometheus-psp.yaml
- helm/prometheus-meta-operator/templates/prometheus-rbac.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- service/controller/resource/rbac/create.go
- service/controller/resource/rbac/delete.go
- service/controller/resource/rbac/resource.go
- service/controller/resource/resource.go
https://github.com/giantswarm/giantswarm/issues/23027
I have:
> Fix psp names

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/13342
I have:
> Add service priority as a tag in opsgenie alerts

- pkg/domain/proxy.go
- service/controller/clusterapi/controller.go
- service/controller/legacy/controller.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/remotewrite/controller.go
- service/controller/remotewrite/resource.go
- service/controller/resource/alerting/alertmanagerconfig/resource.go
- service/controller/resource/alerting/heartbeatwebhookconfig/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/prometheusremotewrite/resource.go
- service/controller/resource/prometheusremotewrite/resource_test.go
- service/controller/resource/resource.go
- service/service.go
This is boyscouting but I'm positive this will help when moving out of operatorkit
I have:
> Refactor internal Proxy configuration

- go.mod
- go.sum
- service/controller/resource/alerting/alertmanager/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanager/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanager/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanager/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanager/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/certificates/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/resource.go
- service/key/key.go
> Fix secret issues on CAPI

- CHANGELOG.md
- service/controller/resource/alerting/heartbeatwebhookconfig/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/resource.go
- service/key/key.go
> Add External Labels to RW config

- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/key/key.go
Adding missing labels from the agent metrics
I have:
> Add organization and service_priority labels

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
We have some trouble with kustomization controller and we'd benefit from some container-level metrics.
I have:
> Added cadvisor scraping for `flux-*` namespaces.

- README.md
Prometheus Volume size docs
Ref: https://github.com/giantswarm/giantswarm/issues/23670
> Add docs for prometheus volume size

- CHANGELOG.md
- service/controller/managementcluster/resource.go
- service/controller/resource/resource.go
- service/controller/resource/wrapper/cleanup/error.go
- service/controller/resource/wrapper/cleanup/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/24222
> Cleanup rw old secrets

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/24059
I have:
> Fix scraping of controller manager and scheduler on MCs

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- go.mod
- pkg/unittest/input/case-1-awsconfig.golden
- pkg/unittest/input/case-2-azureconfig.golden
- pkg/unittest/input/case-3-kvmconfig.golden
- pkg/unittest/input/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
Fixing https://github.com/giantswarm/giantswarm/issues/23130#issuecomment-1308958421
I have:
> Remove targets scraped by the agent

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/24121
Ref: https://github.com/giantswarm/prometheus-rules/pull/497
> Add Inhibition rule for CAPI clusters that runs prometheus-agent

- CHANGELOG.md
- service/controller/managementcluster/resource.go
> Fix reconciliation on vintage MCs

- .circleci/config.yml
- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
> Add CAPZ provider support

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/24062
* do not send inhibitions to slack
* do not send heartbeat to slack
> Sending less alerts into Atlas alert slack channels

- CHANGELOG.md
- README.md
Didn't find where it was documented, so I added it.
I have:
> README: explain how to regenerate tests

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/templates/pod-monitor.yaml
- helm/prometheus-meta-operator/templates/priority-class.yaml
- helm/prometheus-meta-operator/templates/prometheus-rbac.yaml
- service/controller/resource/monitoring/prometheus/resource.go
Goes hand in hand with https://github.com/giantswarm/observability-bundle/pull/18/
I have:
> Change label selector for mc PM and SMs

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
> Support agent on CAPVCD

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/20661
I have:
> alert templating: list of firing instances

- CHANGELOG.md
- service/controller/managementcluster/resource.go
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/resource.go
> Add proxy support to remote write endpoint consumers

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
towards https://github.com/giantswarm/giantswarm/issues/25340
I have:
> add source and target matchers for stack_failed label

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/deployment.yaml
- helm/prometheus-meta-operator/values.yaml
- service/controller/resource/etcd-certificates/resource.go
- service/controller/resource/etcd-certificates/source.go
- service/controller/resource/etcd-certificates/target.go
Towards https://github.com/giantswarm/giantswarm/issues/25713
> Fix etcd-certs

- CHANGELOG.md
- service/controller/managementcluster/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/25713
> Pass the missing Provider property to

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/25909
Explantation: https://github.com/giantswarm/giantswarm/issues/25909#issuecomment-1433320441
> Use resource.Quantity.AsApproximateFloat64() instead of AsInt64()

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/25877
This is a Proposal
Explanation: https://github.com/giantswarm/giantswarm/issues/25877#issuecomment-1437140886
Testing: Tested on testing clusters: gauss, gohan, golem
> Improve VPA maxAllowedCpu

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/25877#issuecomment-1440302764
Ref: https://github.com/giantswarm/giantswarm/issues/25877#issuecomment-1440302764
> getMaxCPU use 50% of the node allocatable CPU

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/25940 and https://github.com/giantswarm/giantswarm/issues/18281
I have:
> Find Prometheus Rules in all namespaces

- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Reverts giantswarm/prometheus-meta-operator#1270. We are getting too much spam in the slack channel :)
> Revert "Add Team Teddyfriends"

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Due to a bad oncall, I forgot to double check that I changed the label everywhere
I have:
> Fix forgotten ksm down source labels

- .circleci/config.yml
- .nancy-ignore
- CHANGELOG.md
towards https://github.com/giantswarm/giantswarm/issues/26826
(this PR is generated automatically, any whitespace changes are due to yq correcting yaml formatting)
> stop pushing to openstack-app-collection

- .nancy-ignore
- CHANGELOG.md
- helm/prometheus-meta-operator/templates/rbac.yaml
- pkg/nodecounter/nodecounter.go
- service/controller/resource/monitoring/remotewriteconfig/create.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/remotewriteconfig/shards.go
- service/controller/resource/monitoring/remotewriteconfig/shards_test.go
- service/key/key.go
- service/service.go
Towards https://github.com/giantswarm/giantswarm/issues/26987
I have:
> Implement prometheus agent sharding

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/26583
I have:
> Add alert routing for team bigmac

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Removing limits was a dubious choice
I have:
> revert cpu limit removal

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
> Move hydra alerts to phoenix

- .nancy-ignore
- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
Towards: https://github.com/giantswarm/giantswarm/issues/27314
Scrape new targets in legacy vault VMs
I have:
> Vault backups exporter

- CHANGELOG.md
- go.mod
- go.sum
- pkg/prometheusquerier/querier.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/remotewriteconfig/shards.go
- service/controller/resource/monitoring/remotewriteconfig/shards_test.go
> Change shard computation based on the number of head series

- .nancy-ignore
- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteconfig/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/27461
I have:
> Fix race condition between Prometheus and Shard configuation

- CHANGELOG.md
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
Fixes https://github.com/giantswarm/giantswarm/issues/27933
I have:
> [#27933] Remove aws-load-balancer-controller from the list of ignored targets

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- pkg/template/template.go
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-6-cluster-api-eks.golden
> Support absolute Grafana dashboard urls

- CHANGELOG.md
- pkg/remotewrite/configuration/utils.go
> revert max shard change

- .nancy-ignore
- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-psp.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-rbac.yaml
- helm/prometheus-meta-operator/templates/prometheus/prometheus-psp.yaml
- helm/prometheus-meta-operator/templates/prometheus/prometheus-rbac.yaml
- helm/prometheus-meta-operator/templates/psp.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- helm/prometheus-meta-operator/values.schema.json
- helm/prometheus-meta-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28337
This PR adds a new switch for PSP disablement to transition to PSS
I have:
> Disable psp switch

- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-azure-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-eks-v18.golden
> switch label source for opsgenie-router

- CHANGELOG.md
- examples/remotewrite.yaml
- helm/prometheus-meta-operator/templates/prometheus/prometheus-psp.yaml
- pkg/remotewrite/configuration/type.go
- pkg/remotewrite/configuration/utils.go
- service/controller/resource/monitoring/remotewritesecret/create.go
towards https://github.com/giantswarm/giantswarm/issues/28239
I have:
> Handle remoteTimeout in RemoteWrite secret and set it to 60s

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-azure-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-eks-v18.golden
towards https://github.com/giantswarm/giantswarm/issues/29263
I have:
> Fix alertmanager config

- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/resource.go
@QuentinBisson 
Some fixes for your PMO branch.
> fix forgotten verticalpodautoscaler.Config

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource_test.go
> Fix VPA for latest prom-operator

- CHANGELOG.md
- service/controller/resource/ciliumnetpol/resource.go
> Add missing grafana cloud port

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
This inhibition is unused and has been waiting for an implementation in ages
I have:
> Remove unused scrape_timeout inhibition

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
Towards: https://github.com/giantswarm/giantswarm/issues/30963
Point Alert source link to Mimir alerting UI when Mimir is enabled
> set Alert source link to Mimir alerting UI

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-ingress.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-tls-secret.yaml
- helm/prometheus-meta-operator/templates/ingress-oauth.yaml
- helm/prometheus-meta-operator/templates/prometheus/prometheus-tls-secret.yaml
> Reverse alertmanager and prometheus ingress removal

- CHANGELOG.md
- service/controller/managementcluster/resource.go
Fixes PMO issues on goat as for some weird reasons those resources were skipped when prepping the mimir migration:
```
:"org-giantswarm/goat","resource":"remotewriteingressauth","stack":{"kind":"remoteWriteNotFound","stack":[{"file":"/root/project/pkg/remotewrite/configuration/utils.go","line":31}]},"time":"2024-06-19T14:51:39.296211+00:00","version":"1395586502"}
{"caller":"github.com/giantswarm/micrologger@v1.1.1/logger.go:88","controller":"prometheus-meta-operator-management-cluster-controller","event":"update","level":"error","loop":"0","message":"retrying due to error","object":"org-giantswarm/goat","resource":"remotewriteingressauth","stack":{"kind":"remoteWriteNotFound","stack":[{"file":"/root/project/pkg/remotewrite/configuration/utils.go","line":31},{"file":"/root/project/service/ …
```
> fix-missed-resource

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
This PR removes unused inhibitions
I have:
> remove unused inhibitions

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
Towards https://github.com/giantswarm/prometheus-rules/pull/1207#discussion_r1660709836
This PR adds the new inhibition configuration that was added https://github.com/giantswarm/prometheus-rules/pull/1278
I have:
> configure new node inhibitions

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
Towards: https://github.com/giantswarm/giantswarm/issues/31601
> Rename tinkerers alerts to tenet

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
Towards: https://github.com/giantswarm/giantswarm/issues/31780
This PR adds the customer label to OpsGenie alerts.
> add customer label to OpsGenie alerts

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
Follow up of https://github.com/giantswarm/prometheus-rules/pull/1515#diff-3a29b0925408184ef087dc0659262542a1519dd676b4b5a0afbf23b4afcc6703 towards https://github.com/giantswarm/giantswarm/issues/28089
This PR takes into account the new alert annotations :)
I have:
> Configure grafana built-in annotations to improve our oncall experience
