giantswarm/prometheus-meta-operator

- helm/prometheus-meta-operator/templates/rbac.yaml
- service/controller/controller_resource_set.go
- service/controller/resource/frontend/create.go
- service/controller/resource/frontend/delete.go
- service/controller/resource/frontend/error.go
- service/controller/resource/frontend/resource.go
- service/controller/resource/service/create.go
- service/controller/resource/service/delete.go
- service/controller/resource/service/error.go
- service/controller/resource/service/resource.go
Closes https://github.com/giantswarm/giantswarm/issues/8155
```
NAME                                     AGE
prometheus.monitoring.coreos.com/4ywny   4h
NAME                                                              AGE
servicemonitor.monitoring.coreos.com/kubernetes-apiserver-4ywny   4h
NAME                                READY   AGE
statefulset.apps/prometheus-4ywny   2/2     4h
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/frontend   2/2     2            2           66s
NAME                       HOSTS
ADDRESS   PORTS   AGE
ingress.extensions/4ywny   4ywny-prometheus.g8s.geckon.gridscale.kvm.gigantic.io
80      66s
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)
AGE
service/prometheus            ClusterIP …
```
> Adds cortex frontend

- helm/prometheus-meta-operator/templates/_resource.tpl
- helm/prometheus-meta-operator/templates/rbac.yaml
- helm/prometheus-meta-operator/values.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/10899
* change chart namespace to monitoring
* remove old chart resources definition
> move to monitoring namespace

- service/controller/resource/alert/rules/apiserver.go
- service/controller/resource/prometheus/resource.go
- service/controller/resource/servicemonitor/services.go
- service/key/key.go
Towards: https://github.com/giantswarm/giantswarm/issues/10898
Since we only read name of the given CR as cluster name, let's use the meta.Objet interface instead of the full v1alpha2.Cluster object. So we can later pass different CRs (awsconfig, azureconfig, kvmconfig) and re-use all resources.
> use metav1.Object interface instead of v1alpha2.Cluster object

- helm/prometheus-meta-operator/templates/rbac.yaml
- service/controller/awsconfig/controller.go
- service/controller/clusterapi/controller.go
- service/controller/resource/alert/create.go
- service/controller/resource/alert/delete.go
- service/controller/resource/certificates/create.go
- service/controller/resource/certificates/delete.go
- service/controller/resource/frontend/create.go
- service/controller/resource/frontend/delete.go
- service/controller/resource/frontend/resource.go
- service/controller/resource/ingress/create.go
- service/controller/resource/ingress/delete.go
- service/controller/resource/namespace/create.go
- service/controller/resource/namespace/delete.go
- service/controller/resource/prometheus/create.go
- service/controller/resource/prometheus/delete.go
- service/controller/resource/resource.go
- service/controller/resource/service/create.go
- service/controller/resource/service/delete.go
- service/controller/resource/servicemonitor/create.go
- service/controller/resource/servicemonitor/delete.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/10898
* change: move controller.NewController to controller/clusterapi.NewController
* change: move controller.newResources to resources.New
* add: awsconfigController
* change: from v1beta1.Deployment to v1.Deployment
* rbac: move from `extensions/v1beta1.deployment` to `apps/v1.deployment`
* rbac: add awsconfigs.provider.giantswarm.io (watch, get, list, update, patch)
* logs: add log message to every resources
Tested on ginger
4 TCs
```
$ gsctl list clusters
ID      ORGANIZATION   NAME                              RELEASE   CREATED
gds6i   giantswarm     theo-monitoring2                  11.0.1    2020 Jun 02, 13:55 UTC
jcqj9   giantswarm     vaclav-test-ha-master-id          12.0.1    2020 Jun 02, 07:23 UTC
t0d0x   giantswarm …
```
> Watch awsconfig CRs

- helm/prometheus-meta-operator/templates/deployment.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/11702
Given that we encoutered capacity issues on CPs, this PR set `prometheus-meta-operator` replicas to 0 so nothing is deployed and we do not run into troubles.
> set prometheus-meta-operator replicas to 0

- CHANGELOG.md
- service/controller/resource/generic/create.go
Fixes the following error
```
W 06/24 09:03:08 /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/h4d6v alert retrying due to error | operatorkit/resource/wrapper/retryresource/basic_resource.go:59 | controller=clusterapi-controller | event=update | loop=37 | stack=map[annotation:prometheusrules.monitoring.coreos.com "example-rules" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update kind:unknown stack:[map[file:/root/project/service/controller/resource/generic/create.go line:31] map[file:/go/pkg/mod/github.com/giantswarm/operatorkit@v1.0.0/resource/wrapper/retryresource/basic_resource.go line:52]]] | version=80098004
```
> generic: fix invalid resource version error

- service/controller/resource/servicemonitor/service/nginx-ingress-controller.go
Towards: https://github.com/giantswarm/giantswarm/issues/10905
The label selector to use is `app.kubernetes.io/name=nginx-ingress-controller`.
The previously used `k8s-app=nginx-ingress-controller` is only used on control planes.
> fix nginx-ingress-controller target

- service/controller/resource/servicemonitor/service/nginx-ingress-controller.go
Towards: https://github.com/giantswarm/giantswarm/issues/10905
In ordre for the nginx-ingress-controller target to work I had to apply the same relabeling logic than the one we have in g8s-prometheus: https://github.com/giantswarm/prometheus-config-controller/blob/0c80a5177c523a75068e9a2c44766bb548013c74/service/controller/v1/prometheus/scrapeconfig.go#L749-L752
This is because it is not possible to reach TC components from the CP. When prometheus finds the nginx-ingress-controller pods via the TC k8s api, it grabs the ip and trys to reach nginx pod using its ip which is not possible in our setup. In order to reach nginx we have to go via the TC api proxy.
Also note that nginx exposes metrics on port `10254`.
Successfully tested on godmsack
> Fix nginx ingress target port

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/deployment.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/12001
/!\ Only merge and release after `argali` situation is fixed: https://github.com/giantswarm/giantswarm/issues/12118
> scale back to 1 replicas

- service/controller/resource/prometheus/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/12251.
Memory requirements for Prometheus container depend on a couple of
factors which contribute to the fact that 200M was too low for some
installations causing Prometheus to get OOM killed as it hit the limit
shortly after startup. This in turn caused crash looping, which in turn
increased storage requirements for the WAL files.
> Bump memory limit for Prometheus containers to 1G

- .circleci/config.yml
This makes us spend wait too much time waiting for CI, so let's run as many job as possible in parallel (quay, aliyun, app-catalog) and only wait/require the ones we need during releases.
> ci: do not wait for aliyun

- CHANGELOG.md
- service/controller/clusterapi/controller.go
- service/controller/legacy/controller.go
Towards https://github.com/giantswarm/giantswarm/issues/12550
I followed the practice defined https://github.com/giantswarm/aws-operator/blob/02d8199912361284bffde9d6d034998baa6fe5ba/service/controller/control_plane.go#L115
> Rename controller names

- Documentation/targets.md
Towards; https://github.com/giantswarm/giantswarm/issues/12995
I do not really know how to track down which giantswarm releases are impacted by docker and nginx-ingress-controller not being scrapped.
> add target doc

- flag/service/etcd/etcd.go
- flag/service/installation/installation.go
- flag/service/service.go
- flag/service/vault/vault.go
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- main.go
Towards: https://github.com/giantswarm/giantswarm/issues/11723
Add installation info:
- installation name
- etcd host and certificates path
- vault address
Tested on `gauss`
```yaml
apiVersion: v1
data:
config.yml: |
server:
enable:
debug:
server: true
listen:
address: 'http://0.0.0.0:8000'
service:
kubernetes:
address: ''
inCluster: true
tls:
caFile: ''
crtFile: ''
keyFile: ''
prometheus:
baseDomain: prometheus.g8s.gauss.eu-west-1.aws.gigantic.io
storage:
createPVC: true
size: 20Gi
provider:
kind: aws
installation:
name: gauss
vault:
host: vault.gauss.eu-west-1.aws.gigantic.io
etcd:
host:  etcd.gauss.eu-west-1.aws.gigantic.io:2379
ca:  /etc/kubernetes/ssl/etcd/client-ca.pem
crt:  /etc/kubernetes/ssl/etcd/client-crt.pem
key:  /etc/kubernetes/ssl/etcd/client-key.pem
kind: ConfigMap …
```
> Installation info

- pkg/unittest/error.go
- pkg/unittest/unittest.go
Towards: https://github.com/giantswarm/giantswarm/issues/12981
* Remove some debug printing
* Add comments to explain how uniitest.Runner works
> unittest: remove print, add comments

- pkg/unittest/input/case-1-awsconfig.golden
- pkg/unittest/input/case-2-azureconfig.golden
- pkg/unittest/input/case-3-kvmconfig.golden
- pkg/unittest/input/case-4-control-plane.golden
- pkg/unittest/unittest.go
- service/controller/resource/namespace/test/case-1-awsconfig.golden
- service/controller/resource/namespace/test/case-2-azureconfig.golden
- service/controller/resource/namespace/test/case-3-kvmconfig.golden
- service/controller/resource/namespace/test/case-4-control-plane.golden
- service/key/key.go
Towards: https://github.com/giantswarm/giantswarm/issues/12981
Fix an issue where test would fail with a misleading error when a file is missing.
```
$ go test -v ./service/controller/resource/namespace
=== RUN   TestNamespace
=== RUN   TestNamespace/case-0-cluster-api.golden
=== RUN   TestNamespace/#00
unittest.go:100: TestFunc: wrong type error: '<nil>' does not implements '<nil>'
=== CONT  TestNamespace
resource_test.go:28: open /home/theo/src/github.com/giantswarm/prometheus-meta-operator/service/controller/resource/namespace/test/case-1-awsconfig.golden: no such file or directory
--- FAIL: TestNamespace (0.00s)
--- PASS: TestNamespace/case-0-cluster-api.golden (0.00s)
--- FAIL: TestNamespace/#00 (0.00s)
FAIL
FAIL    github.com/giantswarm/prometheus-meta-operator/service/controller/res …
```
> improve unit test error handling

- files/templates/_apiserver.yaml
- files/templates/_tlsconfig.yaml
- files/templates/_tlsconfig_skip.yaml
- files/templates/additional-scrape-configs.template.yaml
Towards: giantswarm/giantswarm#13443
* move target tlsconfig to separate template
* move api server config to separate template
Removed another 270 lines from additional-scrape-config.
> more scrape config improvements

- CHANGELOG.md
- go.mod
- service/controller/resource/promxy/create.go
- service/controller/resource/promxy/resource.go
- service/controller/resource/promxy/types.go
tested on ginger
```yaml
global:
scrape_interval: 1m
scrape_timeout: 10s
evaluation_interval: 5s
external_labels:
source: promxy
remote_write:
- url: http://localhost:8083/receive
remote_timeout: 30s
queue_config:
capacity: 500
max_shards: 1000
min_shards: 1
max_samples_per_send: 100
batch_send_deadline: 5s
min_backoff: 30ms
max_backoff: 100ms
promxy:
server_groups:
- remote_read: true
remote_read_path: api/v1/read
http_client:
dial_timeout: 200ms
scheme: http
labels:
cluster_id: ginger
installation: ginger
provider: aws
relabel_configs:
- source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_managed_by, __meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app_kubernetes_io_instance]
separator: ;
regex: prometheus-meta-operator;prometheus;ginger …
```
> fix promxy config marshaling

- CHANGELOG.md
- service/controller/control-plane/resource.go
- service/controller/resource/resource.go
This PR fixes an issue with the order of resources.
volumeresize fails because it does not find the statefulset, prometheus-operator fails to create statefulset because additional scrape configs is not present.
prometheus-meta-operator logs
```
D 10/14 09:30:12 /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/ykc2i volumeresizehack checking if pvc need to be re-created | prometheus-meta-operator/service/controller/resource/volumeresizehack/create.go:23 | controller=prometheus-meta-operator-cluster-api-controller | event=update | loop=14 | version=38155263
E 10/14 09:30:12 /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/ykc2i failed to reconcile | operatorkit/v2/pkg/controller/controller.go:305 | controller=prometheus-meta-operator-cluster-api-controller | …
```
> re-order resources

- main.go
Fix panic error (probably due to bad merge)
This PR fixes the following startup error
```
panic: daemon flag redefined: service.prometheus.basedomain
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc00020f500, 0xc000656500)
/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x807
github.com/spf13/pflag.(*FlagSet).VarPF(0xc00020f500, 0x1d246a0, 0xc00058f7c0, 0xc000227160, 0x1d, 0x0, 0x0, 0x1aab43e, 0x39, 0xc00058f7c0)
/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).VarP(...)
/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc00020f500, 0xc00058f7c0, 0xc000227160, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x1aab43e, 0x39)
/go/pkg/mod/github.com/spf13/pflag@v1.0.5/string.go:42 +0xad …
```
> fix panic: redefined service.prometheus.basedomain

- go.mod
- go.sum
- service/controller/resource/heartbeatrouting/receiver/receiver.go
- service/controller/resource/heartbeatrouting/receiver/receiver_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/13302
Needs: https://github.com/giantswarm/prometheus-meta-operator/pull/177
This PR add the `heartbeatrouting/receiver` resource in charge of managing the alertmanager receiver for hearteat. Which basically boils down to configuring a new opsgenie heartbeat endpoint in alertmanager.
> add heartbeatrouting/receiver sub resource

- service/controller/resource/heartbeatrouting/route/error.go
- service/controller/resource/heartbeatrouting/route/route.go
- service/controller/resource/heartbeatrouting/route/route_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/13302
Needs: https://github.com/giantswarm/prometheus-meta-operator/pull/177
This PR add the `heartbeatrouting/route` resource in charge of managin the alertmanager route for hearteat. Which basically map a heartbeat alert to its receiver/opsgenie endpoint.
> add heartbeatrouting/route sub resource

- CHANGELOG.md
- go.mod
- go.sum
- service/controller/control-plane/resource.go
- service/controller/resource/alert/rules/heartbeat.go
- service/controller/resource/heartbeat/create.go
- service/controller/resource/heartbeatrouting/create.go
- service/controller/resource/heartbeatrouting/delete.go
- service/controller/resource/heartbeatrouting/error.go
- service/controller/resource/heartbeatrouting/helpers.go
- service/controller/resource/heartbeatrouting/receiver/receiver.go
- service/controller/resource/heartbeatrouting/receiver/receiver_test.go
- service/controller/resource/heartbeatrouting/resource.go
- service/controller/resource/heartbeatrouting/route/route.go
- service/controller/resource/heartbeatrouting/route/route_test.go
- service/controller/resource/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/13302
Needs: https://github.com/giantswarm/prometheus-meta-operator/pull/177 https://github.com/giantswarm/prometheus-meta-operator/pull/178 https://github.com/giantswarm/prometheus-meta-operator/pull/179
This PR adds `heartbeatrouting` resource in charge of configuring alertmanager to correctly route new heartbeats to their respective endpoints in opsgenie.
> add heartbeatrouting resource

- service/controller/resource/alert/create.go
- service/controller/resource/alert/delete.go
- service/controller/resource/alert/resource.go
- service/controller/resource/alert/rule_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/13092
Add test to identify invalid/wrongly formatted rules files.
Here is a test run with some invalid rules.
```diff
diff --git a/files/templates/rules/alerts/prometheus-meta-operator.yml b/files/templates/rules/alerts/prometheus-meta-operator.yml
index ccd1f5f..8658bc2 100644
--- a/files/templates/rules/alerts/prometheus-meta-operator.yml
+++ b/files/templates/rules/alerts/prometheus-meta-operator.yml
@@ -48,3 +48,21 @@ spec:
annotations:
description: Labelling schema is invalid.
---
+kind: bob
+---
+apiVersion: monitoring.coreos.com/v1
+kind: PrometheusRule
+metadata:
+  name: alice
+  namespace: {{ .Namespace }}
+  labels:
+    app.kubernetes.io/name: "prometheus"
+    app.kubernetes.io/managed-by: {{ .ManagedBy }}
+ …
```
> Implement test for alert rules

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/14076
New prometheus eat less memory but still they might kill master node. And this was observed multiple times already.
To prevent this, this PR adds soft node affinity which would prefer not scheduling on master but not prevent it.
> prefer scheduling prometheus on non master nodes

- service/controller/resource/alert/resource.go
fixes following error: unknown: html/template: pattern matches no files: `/opt/prometheus/meta-operator/files/templates/rules/**/*.yml`
> fix wrong path in alert resource

- service/controller/resource/alert/create.go
Fixes the following error: unknown: prometheusrules.monitoring.coreos.com "service-level" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
This was due to the created object not being stored back into `currentRule` variable, which lead to :
1. the rule being updated right after its creation
2. resourceVersion being empty
> fix alert creation

- helm/prometheus-meta-operator/templates/configmap.yaml
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/resource_test.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
Writing to cortex is not ready to be released yet, it has to be disabled
in g8s-prometheus first, but we want to make sure other fixes and
features are 100% first.
> Make writing to Cortex optional and disable it

- CHANGELOG.md
- go.mod
- service/controller/resource/heartbeat/resource.go
heartbeat client logs error messages. Let's remove that because we do take care of those already and this is polluting our logs.
We cannot pass it a logger because it uses a totally different logger (logrus vs micrologger).
```
D 11/12 11:28:59 /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/c0vce heartbeat checking if heartbeat exists | prometheus-meta-operator/service/controller/resource/heartbeat/create.go:16 | controller=prometheus-meta-operator-cluster-api-controller | event=update | loop=27 | version=53241904
ERRO[2020-11-12T11:29:00.137839877Z] Error occurred with Status code: 404, Message: Heartbeat not found, Took: 0.008000, RequestId: 5e3a44f6-cf20-4005-b3b5-17fe8897b972
D 11/12 11:29:00 /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/clusters/c0vce heartbeat …
```
> set heartbeat client log level to fatal

- pkg/project/project.go
- pkg/project/version_bundle.go
Not sure how it got in here as it was replaced in all operators as part
of VOO refactoring.
Currently it's causing _prometheus-meta-operator_ to report incorrect
version of itself via `prometheus-meta-operator version` and via the
`giantswarm_build_info` metric (reports `version="0.0.1"`).
This fixes it by removing all references to `bundleVersion` with
`version` which is maintained in `project.go` via CI.
> Replace `bundleVersion` with `version`

- pkg/unittest/unittest.go
- service/controller/resource/alert/rule_test.go
- service/controller/resource/scrapeconfigs/resource_test.go
Hello there was this little patch abandonned somewhere on my disk.
I think it's worth having this, it helps with writting unit tests.
> move project root logic into unnitest.ProjectRoot

- .circleci/config.yml
I keep seeing failures in CI
Let's upgrade CI machine from medium (2cpu 4GB) to large (4 cpu 8GB)
> upgrade to large circleci docker

- .github/workflows/zz_generated.create_release.yaml
- .github/workflows/zz_generated.create_release_pr.yaml
- .github/workflows/zz_generated.gitleaks.yaml
Try and fix and issue during release creation
```
Error: Unable to process command '::add-path::/opt/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
> update github workflow

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Reduced number of metrics ingested from nginx-ingress-controller in order to
reduce memory requirements of Prometheus.
Closes: https://github.com/giantswarm/giantswarm/issues/14660
> Drop highest cardinality nginx metrics

- helm/prometheus-meta-operator/templates/priority-class.yaml
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
This will allow scheduler to prioritise Prometheus over other apps and
allow it to re-schedule pods with less constraints to make nodes in
specific zone required by a Prometheus pod (by placement of its data
volume) available.
Closes: https://github.com/giantswarm/giantswarm/issues/14798
> Add Pod priority class for Prometheus pods

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/alertmanager.rules.yml
Adding https://github.com/giantswarm/g8s-prometheus/commit/81361e3adda538584e0d7564c4ef6cb31e6ba879 before removing the atlas alerts from g8s-prometheus
> Ignore slack in alertmanagernotificationsfailing alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/configmap.yaml
Signed-off-by: QuentinBisson <quentin@giantswarm.io>
I upgraded the recording rules from g8s-prometheus.
I did not see any that we could  but a second pair of eyes could be useful
> Reenable cortex remote write

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/up.rules.yml
The older setup had the metric labelled with `app_name="gatekeeper-app"`, while the newer on has `app="gatekeeper-app"`. This aligns the alert with the new labelling schema.
I have:
> Fixes labels for gatekeeper alert

- CHANGELOG.md
- service/controller/control-plane/resource.go
- service/controller/resource/ingress/resource.go
- service/controller/resource/ingress/test/case-0-cluster-api.golden
- service/controller/resource/ingress/test/case-1-awsconfig.golden
- service/controller/resource/ingress/test/case-2-azureconfig.golden
- service/controller/resource/ingress/test/case-3-kvmconfig.golden
- service/controller/resource/ingress/test/case-4-control-plane.golden
- service/controller/resource/ingress/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/resource.go
- service/controller/resource/tlscleanup/create.go
- service/controller/resource/tlscleanup/delete.go
- service/controller/resource/tlscleanup/error.go
- service/controller/resource/tlscleanup/resource.go
This is unnecessary as it's enough for a single `Ingress` resource to
specify TLS configuration for a host, and in specific circumstances it
can in fact cause problems like an orphaned `Ingress` resource can
prevent an ingress-controller from picking up updated certificates.
This change removes copying of TLS certificates and duplicating TLS
configuration from `Ingress` resources, instead relying on the global
Prometheus `Ingress` (currently maintained in _g8s-prometheus_) being
the source-of-truth for the TLS configuration.
Closes: https://github.com/giantswarm/giantswarm/issues/14951
> Don't copy TLS certs to per-cluster namespaces

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/inhibit.management-cluster.rules.yml
towards https://github.com/giantswarm/giantswarm/issues/15764
To avoid pages that happens right after the update of a cluster.
I am adjusting the inhibition alert to inhibit the alert 10 mins after the update finished.
We often see an update finished but the error counters are still high or error budged be still depleted right after the update finished and this causes pages that resolve in a few minutes. 
function `changes()` will be equal to 1 in case there was a change of the value over a period of the time (in our case 10 minutes)
So when the update finishes the value of the metric will change from 1 to 0 but the inhibition will still work for 10 minutes. This will have no effect on the start of the inhibition since we don't drop the old rules.
I have:
> inhibit-updating-10min-after

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
Refactor the EBSVolumeMountErrors to only need workload cluster info
I have:
> Add firecracker EBSVolumeMountErrors alert

- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
towards https://github.com/giantswarm/giantswarm/issues/15614
merge both alerts into one, since they are related and should page if the critical pod is not running as expected
I have:
> firecracker-cirtical-pod-improvement

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/disk.workload-cluster.rules.yml
This PR:
- removes `PersistentVolumeSpaceTooLow` from WC clusters - it was accidentally added when alerts were migrated over.
I have:
> Don't alert on WC PVs running out of space

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus.rules.yml
That defines `PrometheusCantCommunicateWithKubernetesAPI` alert and it
should apply to Workload Cluster Prometheuses so that we get alerted if
they can't communicate with the Kubernetes API of the cluster they are
responsible for.
Closes: https://github.com/giantswarm/giantswarm/issues/15534
I have:
> Apply prometheus rule group to Workload Clusters

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/management-cluster.rules.yml
The expressions of `ManagementClusterPodPending*` alerts used syntax
`pod~!"..."` which is incorrect and causes _prometheus-operator_
admission controller to reject the rules and fail the deployment.
The correct syntax is `pod!~"..."`. This changes the expressions to use
that.
I have:
> Fix syntax errors in `management-cluster.rules`

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/app.rules.yml
These alerts are usually related to app-operator/chart-operator process and we do not feel responsible for a potential fix in case these components do not work properly so transferring the alert to batman as they manage the process.
discussion happened on slack: https://gigantic.slack.com/archives/CRZN9GLJW/p1614068260030900
The alert is now anyway in `severity: notify` so it does not page, I will leave it to you if you wanna make it paging on not.
I have:
towards https://github.com/giantswarm/giantswarm/issues/15613
> move-cluster-auto-scaler-app-install-failure-to-batman

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
This PR adds one more label ('catalog') to the metrics exported to cortex from `app-exporter`.
> add catalog label to app-exporter metrics

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/docker.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/docker.workload-cluster.rules.yml
We noticed that virtual memory does not make sense and does not reflect what systemd thinks.
I have:
> Use resident memory for docker memory alerting

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/etcdbackup.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/15936
why this change is being introduced: Joe asked for this, who are we to say no to Joe?
I have:
> Avoid alerting for ETCD backups outside business hours.

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
Added:
* 'app' label for metrics going from app-exporter to cortex
> added app label for metrics going from app-exporter to cortex

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.rules.yml
Closes https://github.com/giantswarm/giantswarm/issues/15948
I have:
> fix: Inhibit  when kube-state-metrics is down

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
Towards https://github.com/giantswarm/roadmap/issues/218
In order to know in which installations the legacy authentication mechanism is still in use, we add an aggregation for a new metric of the REST API (added via https://github.com/giantswarm/api/pull/1242).
Plus a tiny bit of comment updating on related aggregations.
I have:
> Add aggregation for use of legacy login method

- CHANGELOG.md
- service/controller/resource/prometheus/resource.go
- service/controller/resource/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/prometheus/test/case-4-control-plane.golden
- service/controller/resource/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/verticalpodautoscaler/test/case-0-cluster-api.golden
- service/controller/resource/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
This is an attempt at raising memory limits, to give prometheus more room and avoid OOMKill.
I raised the memory limit to 1.2 * memory request so (limits: 1.2G, request: 1G). VPA will always conserve this ratio when computing request/limits.
Tested on `anteater`:
```
$ k get po -lapp=prometheus -oyaml|yq -y '.items[].spec.containers[]|select(.name == "prometheus").resources'
limits:
cpu: 163m
memory: 12743276984089m
requests:
cpu: 163m
memory: '10626315661'
$ numfmt --to=si 12743276984 10626315661
13G
11G
```
`12743276984089m` stands for `12743276984.089 bytes` I believe.
I have:
> Increase memory limits to 1.2 * memory requests

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/systemd.management-cluster.rules.yml
- helm/prometheus-meta-operator/templates/prometheus-rules/systemd.workload-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/16428
These alerts are notify only, and are some of the most expensive in terms of memory in the entire system. Removing to improve overall performance (and reduce heartbeat failures).
I have:
> Removes expensive unnecessary systemd rules

- CHANGELOG.md
- go.mod
- go.sum
- pkg/alertmanager/config/config.go
- pkg/alertmanager/config/config_test.go
- pkg/alertmanager/config/coordinator.go
- pkg/alertmanager/config/notifiers.go
- pkg/alertmanager/config/notifiers_test.go
- pkg/prometheus/common/config/config.go
- pkg/prometheus/common/config/http_config.go
- pkg/prometheus/common/config/http_config_test.go
- service/controller/resource/heartbeatrouting/receiver/receiver.go
- service/controller/resource/promxy/test/case-0-cluster-api.golden
- service/controller/resource/promxy/test/case-1-awsconfig.golden
- service/controller/resource/promxy/test/case-2-azureconfig.golden
- service/controller/resource/promxy/test/case-3-kvmconfig.golden
- service/controller/resource/promxy/test/case-4-control-plane.golden
- service/controller/resource/promxy/test/case-5-cluster-api-v1alpha3.golden
The new `follow_redirects` directive in alertmanager config, break PMO which cannot update alertmanager config because the versions do not match anymore
This PR fixes it by aligning dependencies version:
- prometheus/alertmanger@v0.21.0
- prometheus/common@v0.17.0
I have:
> fix follow_redirects

- CHANGELOG.md
- service/controller/resource/verticalpodautoscaler/error.go
- service/controller/resource/verticalpodautoscaler/resource.go
- service/controller/resource/verticalpodautoscaler/resource_test.go
- service/controller/resource/verticalpodautoscaler/test/case-0-cluster-api.golden
- service/controller/resource/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
Similarly to how we specify a maximum amount of memory (to fit within the nodes of a cluster), this PR adds support to specify a maximum amount of CPU.
e.g:
```
$ kubectl get nodes ip-10-0-5-109.eu-central-1.compute.internal -o yaml | grep -A 2 allocatable
f:allocatable:
.: {}
f:attachable-volumes-aws-ebs: {}
--
allocatable:
attachable-volumes-aws-ebs: "25"
cpu: "4"
```
```
$ kubectl -n=gorilla-prometheus get vpa prometheus -o yaml | grep -A 2 maxAllowed
maxAllowed:
cpu: "3"
memory: 14325966Ki
```
I have:
> Adds support for calculating maximum CPU

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/certificate.management-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/15969
This change is introduced because different teams manage MCs in AWS/Azure and on-prem
I have:
> Split ManagementClusterCertificateWillExpireInLessThanTwoWeeks alert

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
Toward https://github.com/giantswarm/giantswarm/issues/16558
We are not fetching cadvisor metrics from the pod located in the `draughtsman` namespace. Since Helm operations are memory-intensive, we would like to know the pattern better by metrics. 
I have:
> Add draughtsman cadvisor metrics

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/15833
While HA Masters makes one master going down not such a big deal, we still want to get notified if this is the case for extended periods of time. (Is 1h appropriate here? We can also do 30 minutes instead.)
I have:
> add alert for HA master down for too long

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
We had a few lines with trailing whitespace in the additional scrape configs, my editor (and me) didn't like it, this PR gets rid of them.
I have:
> Removes unnecessary trailing whitespace

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- helm/prometheus-meta-operator/templates/recording-rules/cortex.rules.yml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
Towards https://github.com/giantswarm/giantswarm/issues/16599
I want to see how many pulls we're doing (as part of reducing overall registry usage), so adding the aggregation. New metric should add time series on the the order of O(nodes), which is fine.
I have:
> Add aggregation for Docker actions

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.rules.yml
Towards: giantswarm/giantswarm#15948
> Fix inhibition of MatchingNumberOfPrometheusAndCluster

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/13725
Kubernetes mixins dashboards in grafana needs the container_network metrics to function
I have:
> Keep container network metrics

- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.rules.yml
to be a bit more readable. No functionality changes.
Towards: https://github.com/giantswarm/giantswarm/issues/15890
I have:
> Format `MatchingNumberOfPrometheusAndCluster` expression

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus-meta-operator.rules.yml
As runbook now exists, ensure the alert will link to it to make it easy
for oncallers to find.
Towards: https://github.com/giantswarm/giantswarm/issues/15890
I have:
> Add runbook link to `MatchingNumberOfPrometheusAndCluster`

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/up.all.rules.yml
This is a preparation for https://github.com/giantswarm/prometheus-meta-operator/pull/505
We are currently getting paged by `kube-state-metrics` down quite a bit for different reasons. This will make it easier for oncallers to quickly identify why the problem is happening.
I have:
> Add kube-state-metrics missing alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/up.all.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/16178
This was just different from the other `Down` metrics. In all others we do not check for `absent`. Could it therefor be that the absent part leads to false pages?
My idea was to just merge this and try it.
I have:
> Remove absent from KSM alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/managed-apps-basic-sli.rules.yml
I have lowered the severity of managed apps alerts since it is mostly not affecting any customer's business
> Lower the severity to notify for managedApp

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/inhibit.all.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/16803
This PR fixes an issue with `InhibitionKubeStateMetricsDown` which does not fires long enough and result in `KubeStateMetricsMissing` firing too early.
* `KubeStateMetricsMissing` fires until at 11:55:35
* `InhibitionKubeStateMetricsDown` fires until 11:53:01, which gives ~2mn for the alert to fire.
* fixed `InhibitionKubeStateMetricsDown` fires until at 11:55:35, which gives no time for the alert to fire.
> fix InhibitionKubeStateMetricsDown not firing longe enough

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/up.all.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/16803
Inhibition for both alert was wrong, this probably caused the false pages.
> inhibit KubeStateMetricsDown and KubeStateMetricsMissing

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/alertmanager-dashboard.rules.yml
Introducing alert for `alertmanager-dashboard` deployment not running, which pages only in business hours.
I have:
> Add alertmanager-dashboard alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/disk.management-cluster.rules.yml
This alert resolves itself very often - Prometheus does disk cleanup, so let's give it more time to do so before alerting
I have:
> Increases duration for prometheus low disk space alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/network.all.rules.yml
- pkg/project/project.go
I have:
This is related to https://github.com/giantswarm/giantswarm/issues/14756. 
This change introduces 3 alerts. One for number of allocated ports, one for orphaned ports, and one for time wait state ports.
This is to help early identify when the node runs out of ports and can start having issues. The limits are set at 90% and 80% in order early notify before there are errors
> Add alerts for alloc orphan and time wait sockets

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/operatorkit.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/17287
Celestial thinks the operatorkit-related alerts shouldn't page during the night.
The reasons behind this are:
- The main reason why this happened in the past was because of expired service principal credentials, and this is not a problem any more
- If this happens for other reasons, they usually are external things (such as azure API being down) and they self solve and we can't do a thing about it
- operatorkit operators are going to disappear because of CAPI
- customer workloads should not be affected or, if they are, should page with more specific alerts.
I have:
> Silence Some celestial alerts outside business hours

- CHANGELOG.md
- service/controller/resource/heartbeatrouting/receiver/receiver.go
- service/controller/resource/heartbeatrouting/receiver/receiver_test.go
AlertManager doesn't do merging itself, which means that if we specify
HTTP config in the receivers (e.g. to specify auth credentials), then
the global config is not used for those receivers.
We want to preserve any options set in the global config which may
specify things like a proxy server to use, which affects the entire
environment.
Towards: https://github.com/giantswarm/giantswarm/issues/17238
I have:
> Merge AlertManager global HTTP config with generated receivers

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus.rules.yml
Prometheus servers running in china seems to never have sent data to cortex, and the alert about remote write never fired for them
So I updated the alert to take into account the `prometheus_remote_storage_metadata_retried_total` metric
> update PrometheusFailsToCommunicateWithRemoteStorageAPI alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/deployment.management-cluster.rules.yml
including `cluster-api-core-unique-webhook` into DeploymentNotSatisfied for AWS.
I have:
> cluster-api-core-unique-webhook

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/prometheus.rules.yml
I got hit with a flap of this, so increasing the duration so we can be more sure that Prometheus can't reach the API
I have:
> Increases duration of Prometheus cant communicate alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/etcd.workload-cluster.rules.yml
towards https://github.com/giantswarm/giantswarm/issues/17199
these seem to page when the cluster is upgrading from single master to multi-master HA, but resolve afterward
I think we should be safe to increase the duration for the alerts, specially fro the DB size
and if the Etcd has really "no leader" we would get paged by tons of other alerts as API would be basically dead
I have:
> increase-time-for-etcd-alerts

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/aws.workload-cluster.rules.yml
Cluster autoscaler restarts are not being monitored.
I have:
> Update Autoscaler rule on restarts

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
VPA takes the maxAllowed to be based on memory request, that means the
request can be set to almost max memory available to the node, but since
the limit is calculated based on the request and multiplied by 1.2 it
means the limit can go higher than available memory.
Prevent this by lowering the maxAllowed value by the request-limit
coefficient.
Towards: https://github.com/giantswarm/giantswarm/issues/17350
I have:
> Fix memory limit to avoid going over node capacity

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/disk.management-cluster.rules.yml
Prometheus does disk cleanup on its own, and can happily go below 10% free disk space on some clusters. 5% doesn't seem to occur on checked clusters. Updating alert threshold to reduce flappiness.
I have:
> Lowers Prometheus disk space alert threshold

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/deployment.workload-cluster.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/17712
I have:
> Add metrics-server deployment to monitored WC components

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/coredns.rules.yml
Towards https://github.com/giantswarm/giantswarm/issues/17712
Adds a business hours alert when CoreDNS has been scaled to its maximum HPA replica count for 2 hours.
I have:
> Add CoreDNSMaxHPAReplicasReached alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/coredns.rules.yml
When max and min number of replicas are the same don't alert. After deploying the new alert we have been paged for clusters where they fix number of max/min replicas. I don't see the point of alert in such a case
I have:
> Polish CoreDNSMaxHPAReplicasReached alert

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/azure.management-cluster.rules.yml
Towards: https://github.com/giantswarm/giantswarm/issues/17763
This PR adds a new alert for azure workload cluster which upgrade takes too long and fixes the alert for creation taking too long.
I have:
> Added/fixed azure WC creation and update failure alerts

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/service-level.rules.yml
Closes https://github.com/giantswarm/giantswarm/issues/17734
To avoid having services alerting that we don't - e.g: in the case where we're still testing a service's service level out, this adds support to opt-in to the service level alert, so we don't get unwanted pages.
See https://gigantic.slack.com/archives/C02MS174K/p1623828191186600 for more context.
I have:
> Moves SLO alert to opt-out

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-rules/service-level.rules.yml
This was too unactionable to be useful
I have:
> Removes ServiceLevelBurnRateTicket alert

- CODEOWNERS
We want to be automatically requested for review of **release** PRs so
that we can advise in case there are reasons to postpone a release, e.g.
in case we want to bundle changes that are about to land, or we're aware
of a problem in the master branch, etc.
Towards: https://github.com/giantswarm/roadmap/issues/352
I have:
> Request team Atlas for review of release PRs

- .circleci/config.yml
To fix an issue with out of date key for pushing to catalog repo.
I have:
> Update Architect to 3.3.0

- CHANGELOG.md
- helm/prometheus-meta-operator/ci/default-values.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
Instead of hardcoding the remote-write URL. This is needed so that we
can override the URL in installations which can't access Grafana Cloud
directly.
Towards: https://github.com/giantswarm/giantswarm/issues/17366
I have:
> Use Grafana Cloud config

- go.mod
- go.sum
This is to fix build failures due to nancy finding a vulnerability in
`github.com/dgrijalva/jwt-go` v3.2.0.
The upstream jwt-go project is no longer maintained and has been
replaced with `github.com/golang-jwt/jwt`, see
https://github.com/dgrijalva/jwt-go/issues/462
I have:
> Replace jwt-go dependency

- go.mod
- go.sum
- pkg/alertmanager/config/coordinator.go
Close https://github.com/giantswarm/prometheus-meta-operator/pull/663
This PR change go-kit/kit/log to go-kit/log as mentionned in the 0.11.0 release.
> use go-kit/log

- CHANGELOG.md
- service/controller/resource/monitoring/ingress/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/ingress/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/ingress/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/ingress/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/ingress/test/case-4-control-plane.golden
- service/controller/resource/monitoring/ingress/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-0-cluster-api.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/namespace/resource.go
- service/controller/resource/namespace/test/case-0-cluster-api.golden
- service/controller/resource/namespace/test/case-1-awsconfig.golden
- service/controller/resource/namespace/test/case-2-azureconfig.golden
- service/controller/resource/namespace/test/case-3-kvmconfig.golden
- service/controller/resource/namespace/test/case-4-control-plane.golden
- service/controller/resource/namespace/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Closes https://github.com/giantswarm/giantswarm/issues/18243
This PR uses the `giantswarm.io/cluster` label already set on the workload cluster namespace to differentciate between workload cluster namespaces and management cluster namespaces
I have:
> Enable usage of service monitors

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-0-cluster-api.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
From https://github.com/giantswarm/g8s-prometheus/pull/1308
Towards https://github.com/giantswarm/giantswarm/issues/13754
We have a `#noise-falco` Slack channel. This sends stuff to it.
I have:
> Add Falco noise slack receiver and route

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- flag/service/prometheus/prometheus.go
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/values.yaml
- main.go
- service/controller/clusterapi/controller.go
- service/controller/legacy/controller.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource_test.go
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/resource.go
- service/service.go
Towards https://github.com/giantswarm/telekom-panamax/issues/104
This change is being introduced so that we can have installation specific scrape configs defined in the `config` repo. This helps PMO to be more general and improves security/privacy by not having customer information defined in a public repo. Discussed in SIG Security here https://gigantic.slack.com/archives/C3S23JE75/p1628529921003700.
I have:
> Add additional scrape configs from installation config

- CHANGELOG.md
- pkg/unittest/input/case-0-cluster-api.golden
- pkg/unittest/unittest.go
- service/controller/clusterapi/controller.go
- service/service.go
AWS only uses `v1alpha2` till now but we switched to `v1alpha3` as stored version.
CRD Webhook converts all `v1alpha2` CR's to `v1alpha3`.
Dropping `v1alpha2` is needed for migration.
I have:
> drop v1alpha2

- CHANGELOG.md
- service/service.go
This PR fixed pmo crashloops when legacy CRD are missing from installations like AWSConfigs, AzureConfigs and KVMConfigs
I have:
> Fix crashloop when missing AWS Config

- CHANGELOG.md
- go.mod
- pkg/unittest/input/case-0-cluster-api.golden
- pkg/unittest/unittest.go
- service/controller/clusterapi/controller.go
- service/service.go
This PR make sure we reconcile v1alpha2 when needed, otherwise prefer v1alpha3.
`puma` only runs cluster v1alpha2
```
$ k --context giantswarm-puma get crd clusters.cluster.x-k8s.io -oyaml|yq -y '.spec.versions[]|{name, storage}'
name: v1alpha2
storage: true
```
> Fix v1alpha2

- CHANGELOG.md
- go.mod
- go.sum
- pkg/alertmanager/config/config.go
- pkg/alertmanager/config/coordinator.go
- pkg/alertmanager/config/notifiers.go
- pkg/prometheus/common/config/config.go
- pkg/prometheus/common/config/http_config.go
This PR upgrade upstream code vendored in this repository :
- pkg/alertmanager/config to v0.23.0
- pkg/prometheus/common/config to v0.30.0
This is to keep things aligned after merging #707
`/!\` Do not merge with squash, once approved merge to master manually. `/!\`
> Upgrade alertmanager/config to v0.23.0

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-0-cluster-api.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/roadmap/issues/546
This PR enables a new inhibition leveraging https://github.com/giantswarm/prometheus-rules/blob/0b1f77f8b1b5a840ad47ff7bb0599b929c737283/helm/prometheus-rules/templates/alerting-rules/inhibit.all.rules.yml#L32 and silencing any alerts labeled `cancel_if_has_no_workers` when the cluster has no worker nodes
I have:
> Inhibition no workers

- CHANGELOG.md
- files/templates/scrapeconfigs/_node_role.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/18779
Among all exporters that are discovered using the prometheus' `kubernetes` discovery plugin, only the ones using the `node` role have the node's labels available.
We rely on the nodes' "role" label to detect the role of the k8s node so we can't reliably detect this information.
This PR removes the defaulting feature to avoid the wrong default.
I have:
> Avoid defaulting node role

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- Towards https://github.com/giantswarm/giantswarm/issues/20083
- Adds relabel config for app that copies app name annotation to prometheus app label, towards helping managed app monitoring
I have:
> Adding  support for updating app label based on monitoring annotation

- CHANGELOG.md
- go.mod
- pkg/unittest/input/case-0-cluster-api.golden
- pkg/unittest/unittest.go
- service/controller/clusterapi/controller.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/20186
KVM installations do not officially support capi (even though Cluster CRD might be present).
This PR does the following :
- Remove `v1alpha2` capi support
- Disable capi controller on KVM installations
> disable capi controller on kvm

- CHANGELOG.md
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/20186
For each cluster there are both an `AzureConfig` and a `Cluster` CR, since PMO watches both it does reconcile both at the same time. Release `15.1.3`
```
D 12/21 15:04:45 org-giantswarm/qs9d8 namespace creating | prometheus-meta-operator/service/controller/resource/generic/create.go:17 | controller=prometheus-meta-operator-cluster-api-controller | event=update | loop=16 | version=130980581
D 12/21 15:04:45 org-giantswarm/qs9d8 namespace created | prometheus-meta-operator/service/controller/resource/generic/create.go:35 | controller=prometheus-meta-operator-cluster-api-controller | event=update | loop=16 | version=130980581
D 12/21 15:04:46 default/qs9d8 namespace creating | …
```
> disable legacy controller on aws and azure

- CHANGELOG.md
- service/controller/resource/certificates/resource.go
Closes https://github.com/giantswarm/giantswarm/issues/20257
I have:
> Prevent panic when user in kubeconfig is not matching

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
Allow overriding protocol in scrape config to be able to scrape prometheus operator
I have:
> Allow overriding protocol

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
This PR fixes an issue where duplicate series are found for node-exporter. This happen because we label the target with its pod name, which results in producing multiples series for the same node over time when pods are replaced.
The prometheus memory percentage aggregation rely on the fact that nodes are unique.
> node-exporter target: drop namespace,container, and pod label. keep node label.

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-0-cluster-api.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
Firecracker and Celestial alerts still routing to old slack recievers
I have:
> Replaced firecracker and celestial routing with phoenix

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/configmap.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/21294
Removing trailing right whitespaces result in invalid/broken config and crashlooping PMO.
> do no trail right whitespaces

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfigsecret/test/case-5-cluster-api-v1alpha3.golden
Old matcher types have been deprecated to support a broader scope of regexes
I have:
> Upgrade alertmanager matchers to remove deprecated types

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
Towards: https://github.com/giantswarm/giantswarm/issues/20670
azure-collector takes longer than the default 10s to provide data and that makes it fail very often.
this PR changes the timeout value to a safer 60s and also decreases the interval.
I have:
> Changed scrape_interval to 180s and scrape_timeout to 60s for azure-collector

- CHANGELOG.md
- service/controller/resource/alerting/alertmanager/resource.go
- service/controller/resource/alerting/alertmanager/resource_test.go
- service/controller/resource/alerting/alertmanagerconfig/resource.go
- service/controller/resource/alerting/alertmanagerwiring/resource.go
- service/controller/resource/alerting/heartbeatwebhookconfig/resource.go
- service/controller/resource/etcd-certificates/resource.go
- service/controller/resource/generic/create.go
- service/controller/resource/generic/delete.go
- service/controller/resource/generic/resource.go
- service/controller/resource/monitoring/ingress/v1/resource.go
- service/controller/resource/monitoring/ingress/v1beta1/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/resource_test.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/remotewriteconfig/resource_test.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/namespace/resource.go
- service/controller/resource/namespace/resource_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/21156
Add controller context to generic resource, so we can later re-use it for logging and other purposes.
- pass context from generic resource
- pass context around
- update CHANGELOG
> generic resource context

- service/controller/resource/etcd-certificates/doc.go
- service/controller/resource/etcd-certificates/resource.go
- service/controller/resource/etcd-certificates/source.go
- service/controller/resource/etcd-certificates/target.go
Towards: https://github.com/giantswarm/giantswarm/issues/21156
Move `etcd-certificate` code around and prepare to add openstack support.
- enrich secretCopier with logger and k8sClient
- move getSource to getSourceFromDisk
> prepare etcd certificates

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/21428
after we merge https://github.com/giantswarm/kube-state-metrics-app/pull/132/files with this PR we rewrite the node pool name in `kube_node_info` metric as `nodepool` to make it uniform across providers.
This will be helpful to make SLO alerts nodepool-aware.
I have:
> Kube state metrics nodepool

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
The main node IP as written by the kubelet in the `Node` status field, is unreliable.
In AWS MCs this can be a random POD cidr IP and when that's the case etcd scraping fails.
This PR looks for a label named "ip" in the Node resource and, if present, uses that label for scraping etcd.
The label is set by us on MCs with a well known correct ip address.
This makes scrape success much more likely.
I have:
> Use 'ip' node label as target to scrape etcd on MCs.

- CHANGELOG.md
- README.md
- helm/prometheus-meta-operator/templates/remoteWrites_crd.yaml
Towards https://github.com/giantswarm/roadmap/issues/1109
Deploy remoteWrite CRD with Helm chart.
I have:
> add remoteWrite CRD to helm chart

- CHANGELOG.md
- service/controller/remotewrite/controller.go
- service/controller/remotewrite/resource.go
- service/controller/resource/prometheusremotewrite/create.go
- service/controller/resource/prometheusremotewrite/resource.go
- service/service.go
Issue: https://github.com/giantswarm/roadmap/issues/1169
Adding `HTTP_PROXY` If needed, once set up in the controller. 
I have:
> Supply HTTP proxy in remotewrite config

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/roadmap/issues/1167
This PR changes the current name of the remote write config to match the upcoming resource name ([see](https://github.com/giantswarm/prometheus-remotewrite/pull/3/files#diff-5d9cb907ead68e48ad623375e437680d927f1572d02af17fd55963b5a169b2beR4)).
> change remote write name to grafana-cloud

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/rbac.yaml
Towards: https://github.com/giantswarm/roadmap/issues/1140
Add the `patch` verb for `remoteWrite` resources needed by operatorkit to add finalizers.
> grant remoteWrite patch permission

- CHANGELOG.md
- api/v1alpha1/remoteWrite_types.go
- config/crd/monitoring.giantswarm.io_remotewrites.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- pkg/remotewriteutils/error.go
- pkg/remotewriteutils/util.go
- pkg/remotewriteutils/util_test.go
- service/controller/remotewrite/resource.go
- service/controller/resource/prometheusremotewrite/create.go
- service/controller/resource/prometheusremotewrite/delete.go
- service/controller/resource/prometheusremotewrite/error.go
- service/controller/resource/prometheusremotewrite/resource.go
- service/controller/resource/prometheusremotewrite/resource_test.go
- service/controller/resource/remotewritesecret/create.go
- service/controller/resource/remotewritesecret/delete.go
- service/controller/resource/remotewritesecret/error.go
- service/controller/resource/remotewritesecret/resource.go
Towards https://github.com/giantswarm/roadmap/issues/1180
After adding https://github.com/giantswarm/prometheus-meta-operator/pull/928 
In this PR, I added the logic of the sync.
By adding a new resource `remotewritesecret`.
and implementing `EnsureCreated()` and `EnsureDeleted`
I have:
> Implement sync RemoteWrite Secrets logic

- CHANGELOG.md
- service/controller/resource/remotewritesecret/create.go
Towards https://github.com/giantswarm/roadmap/issues/1180
After https://github.com/giantswarm/prometheus-meta-operator/pull/930 gets merged
We also need to implement the logic of updating secrets once changed in remotewrite CR
I have:
> Update secrets once changed

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
Added `pod_name` as a label to distinguish between multiple etcd pods when running in-cluster (e.g. CAPI)
I have:
> Use pod ip for scrapping etcd on CAPI

- CHANGELOG.md
- files/templates/scrapeconfigs/_cert_exporter_namespace.yaml
- files/templates/scrapeconfigs/_node_exporter_namespace.yaml
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
Closes https://github.com/giantswarm/roadmap/issues/1265
In WCs and the new MCs created for CAPI we deploy `node-exporter` and `cert-exporter` to the `kube-system` namespace. That way WCs and MCs are more similar between them.
But in the vintage product, `node-exporter` and `cert-exporter` are deployed to the `monitoring` namespace for MCs.
This PR changes the logic for `node-exporter` and `cert-exporter` namespaces:
- Use `kube-system` for CAPI MCs and all WC
- Use `monitoring` for vintage MCs
- Assume `aws` and `azure` MCs are vintage (`CAPIManagementCluster` check that is used is checking if the provider is one of cloud-director, gcp, openstack or vsphere, see here https://github.com/giantswarm/prometheus-meta-operator/blob/master/service/key/key.go#L79)
I have:
> Update node-exporter and cert-exporter namespace

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
Team Hydra wants to enable business hours alerts for GCP (CAPG) clusters.
I have:
> Add Team Hydra receiver and route

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
I got alerted that a heartbeat was failing. This happened for a new cluster as the alertmanager config is missing the heartbeat configuration for the new cluster after team hydra was added with a misconfiguration.
I have:
Error in prometheus-operator:
`level=error ts=2022-08-18T13:40:10.373498114Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="Sync \"monitoring/alertmanager\" failed: provision alertmanager configuration: base config from Secret could not be parsed: yaml: unmarshal errors:\n  line 157: field send_resolved not found in type config.plain\n  line 158: field actions not found in type config.plain"`
> Fix Team Hydra notification template

- .nancy-ignore
- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
Relabels the recently added labels `label_topology_kubernetes_io_region` &  `label_topology_kubernetes_io_zone` to `region` & `zone`.
I have:
> scrape-configs: Replace region & zone labels.

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
> scrape-config: Drop original region & zone labels.

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
Move team-shield route so alerts for shield don't go to opsgenie at all, only to their slack.
> move shield route so alerts for shield don't go to opsgenie

- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteingress/v1/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/remotewriteingress/v1/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/remotewriteingress/v1/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/remotewriteingress/v1/test/case-4-control-plane.golden
- service/controller/resource/monitoring/remotewriteingress/v1/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/remotewriteingress/v1beta1/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/remotewriteingress/v1beta1/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/remotewriteingress/v1beta1/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/remotewriteingress/v1beta1/test/case-4-control-plane.golden
- service/controller/resource/monitoring/remotewriteingress/v1beta1/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
I have:
Setting the size to 1M seems to prevent the use of a temporary file for most cases:
```sh
52.211.181.33 - w3r2i [19/Oct/2022:09:40:11 +0000] "POST /w3r2i/api/v1/write HTTP/2.0" 204 0 "-" "Prometheus/2.39.1" 375284 3.564 [w3r2i-prometheus-prometheus-operated-9090] [] 100.64.5.226:9090 0 2.318 204 1fc6808e73a33b63a323eae2eab00468
52.211.181.33 - w3r2i [19/Oct/2022:09:40:12 +0000] "POST /w3r2i/api/v1/write HTTP/2.0" 204 0 "-" "Prometheus/2.39.1" 378376 1.302 [w3r2i-prometheus-prometheus-operated-9090] [] 100.64.5.226:9090 0 0.163 204 793850cf506c84e7b10e0306e4013608
52.211.181.33 - w3r2i [19/Oct/2022:09:40:18 +0000] "POST /w3r2i/api/v1/write HTTP/2.0" 204 0 "-" "Prometheus/2.39.1" 160537 1.189 [w3r2i-prometheus-prometheus-operated-9090] [] 100.64.5.226:9090 0 0.026 204 …
```
> Configure RW client buffer body size

- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
After some experimentation, it seems that either nginx or the prometheus receiver are not able to accept too many requests and setting the number of maxShards to 10 plus an increased capacity (more samples stored per shards and more samples sent per batch) does the trick.
Remote write is not falling behind and the situation appears stable:
For information:
- [MaxShards](https://prometheus.io/docs/practices/remote_write/#max_shards): We currently use only 1 shards (we have only 5 targets so ...) and it's not increasing. I set it to 10 because it can take a bit more when replaying the WAL but it's mostly fine
- [Capacity](https://prometheus.io/docs/practices/remote_write/#capacity): Set to 30000 as it should be 3-10 times the max number of sent samples
- …
> Configure working queueconfig

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager-psp.yaml
Alertmanager was failing to start with these errors:
```
create Pod alertmanager-alertmanager-0 in StatefulSet alertmanager-alertmanager failed 
error: pods "alertmanager-alertmanager-0" is forbidden: PodSecurityPolicy: unable to admit pod:
[
spec.volumes[2]: Invalid value: "projected": projected volumes are not allowed to be used
spec.volumes[2]: Invalid value: "projected": projected volumes are not allowed to be used
spec.volumes[0]: Invalid value: "persistentVolumeClaim": persistentVolumeClaim volumes are not allowed to be used
]
```
Reason: alertmanager is updated with prometheus-operator upgrade, but the PSPs, managed by prometheus-meta-operator, were not updated accordingly.
> Fix alertmanager psp (add projected and downardAPI)

- .nancy-ignore
- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus-psp.yaml
Should fix deployment of prometheus on GCP and CAPA clusters.
Towards https://github.com/giantswarm/giantswarm/issues/24321
I have:
> fix prometheus-psp

- CHANGELOG.md
- service/controller/managementcluster/resource.go
This change is being introduced because CAPI MC clusters will be running the agent as default apps are installing the observability bundle everywhere.
Enabling the remote write receiver on the MC prometheus will ensure we can use service monitors on both CAPI MC and WC and remove the additional scrape config section.
I have:
> Enable remote write receiver for MC prometheus

- CHANGELOG.md
- service/controller/clusterapi/controller.go
- service/controller/managementcluster/resource.go
Fix reconciliation bug to ensure the clusterapi controller only reconciles cluster api workload clusters as it currently reconciles both MC and WC cluster CR.
I have:
> Fix CAPI MC reconciliation

- CHANGELOG.md
- Documentation/targets.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
Towards: https://github.com/giantswarm/giantswarm/issues/24541
App Exporter provides Service Monitor that configures job that is redundant to the `CLUSTER-prometheus/app-exporter-CLUSTER/0`. The target can be  dropped from this job with the `giantswarm.io/monitoring` label set, but setting this label at the same time adds (keeps) target to the `CLUSTER-prometheus/workload-CLUSTER/0` job, still making the App Exporter to be scrapped twice. 
I have:
> Drop job in favor of SM

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
towards https://gigantic.slack.com/archives/C01176DKNP4/p1669133286733979
In CAPI clusters, `vault` is replaced by `sops`.
This PR removes `vault` targets for CAPI clusters from the additional scraping configuration file.
I have:
> Remove 'vault' targets on CAPI clusters

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/case-5-cluster-api-v1alpha3.golden
Towards: https://github.com/giantswarm/giantswarm/issues/24062
This PR configures alertmanager to send non-paging alerts to our slack channels.
#alert-atlas: receive alerts for stable installations
#alert-atlas-test: receive alerts for testing installations
> Send notify alert to Atlas slack channels

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/23130
I have:
> Do not reconcile service monitors in CAPO MCs

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/20661
Revert to markdown so it's looking OK on slack
I have:
> Opsgenie messages: revert to markdown

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource_test.go
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-0-cluster-api.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-1-awsconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-2-azureconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-3-kvmconfig.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-5-cluster-api-v1alpha3.golden
towards: https://github.com/giantswarm/giantswarm/issues/24788
This will make PMO ignore static targets on CAPA MCs, and add namespaceSelector for Prometheus to ignore kube-system.
> Use prometheus-agent on CAPA MCs

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/20661
Noticed instances list is wrong in slack templates as well:
So this should fix it.
I have:
> slack alert templating: fix list of instances

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/roadmap/issues/690
Dashboards links were kind of supported, but not working.
`dashboard` reference has to be built from uid/title, as described in prometheus-rules README. See https://github.com/giantswarm/prometheus-rules/pull/563
I have:
> fix dashboard url

- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Added the `harbor_implementation` receiver in order to send slack alerts to the `#harbor-implementation` channel based on harbor alerts.
Signed-off-by: William Young <will.young@engineerbetter.com>
Co-authored-by: Ajayi Dipo <ajayidipo@ymail.com>
> Add template for harbor slack alerts

- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteingress/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-4-control-plane.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/25049
For prometheus-agent remotewrite to work fine, it has to send data in rather big batches.
We have observed that proper performance requires batches at minimum between 1 to 2 MB big.
And default nginx config limits requests to 1MB.
So let's increase this limit for remotewrite ingress.
I have:
> Remotewrite ingress allows bigger requests

- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/25049
For prometheus-agent remotewrite to work fine, it has to send data in rather big batches.
The previous batch size was too small, let's increase it.
I have to understand the deployment procedure before merging it. I'll probably add stuff in the CHANGELOG when I test it.
I have:
> prometheus-agent: increase max samples per send

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
Fix release 4.20.0 with the missing enable-feature:
```
ts=2023-01-17T11:26:17.244Z caller=dedupe.go:112 component=remote level=error remote_name=63fb6b url=https://prometheus.g8s.icecream.westeurope.azure.gigantic.io/icecream/api/v1/write msg="non-recoverable error" count=6642 exemplarCount=0 err="server returned HTTP status 404 Not Found: remote write receiver needs to be enabled with --enable-feature=remote-write-receiver"
```
I have:
> Fix spec Prometheus : add enable remote-write-receiver (schema 0.62.0)

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/deployment.yaml
towards https://github.com/giantswarm/giantswarm/issues/25713
=> to avoid certificates created as directories when `pmo` is started before systemd unit runs into the node.
I have:
> Fix certificates created as directories rather than files

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
`notify` severity alerts are too many to be actionable for phoenix.
This PR disables them, while enabling the `notify` severity alerts generated by SLOTH only.
I have:
> Send SLO (sloth based) notify level alerts to '#alert-phoenix' Slack channel.

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
This changed was introduced back in #893 and is no longer needed, as there is now a 15mn startupProbe allowing for slow Prometheus with a big WAL data to load.
I have:
> remove prometheus readinessProbe delay

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/25767
Memory limit could go up to 108% of node's memory. And memory exhaustion on node leads to killing node.
This change in codes makes:
* max requests reduced from 90% to 80% node memory
* max limit reduced from 108% to 96% node memory
Maybe we should restrict even more to avoid nodes being killed, but I don't want to go too fast. Step by step.
Also, removed VPA config for `prometheus-config-reloader` and `rules-configmap-reloader`: these containers don't exist, so this config has no effect.
On top of that, we actually have a `config-reloader` container, which is scaled down with default VPA config, and it works well like that.
BTW, found and fixed a bug when our computed maxmemory would give a non-round number of bytes, and VPA …
> adjust VPA settings to prevent prometheus from using all node RAM

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/resource_test.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
VPA settings: changes in 4.24.0 were wrong, resulting in too low limits.
- Previous logic (4.23.0) was right, and limits were 90% node size.
- Comments have been updated for better understanding
- limit has been reverted to 90% node size
- code for CPU limits has been updated to do the same kind of calculations
- tests have been updated for more meaningful results
Towards https://github.com/giantswarm/giantswarm/issues/26142
I have:
> simplified and fixed mem limit calculation

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager/ownership-job/job.yaml
The job also patch the Alertmanager resource to removes the label `managed-by: pmo `
from `alertmanagerConfigSelector`.
If the field doesn't has the label, the job will fail. so deployment will be stuck
> allow ownership job to fail

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Prometheus TSDB size: reduce it to 85% of disk space, to keep space for WAL before alerts fire.
Towards https://github.com/giantswarm/giantswarm/issues/26041
I have:
> Prometheus TSDB size: reduce it to 85% of disk space

- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteingress/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-4-control-plane.golden
- service/controller/resource/monitoring/remotewriteingress/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/remotewriteingress/test/externaldns/case-1-awsconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/externaldns/case-2-azureconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/externaldns/case-3-kvmconfig.golden
- service/controller/resource/monitoring/remotewriteingress/test/externaldns/case-4-control-plane.golden
- service/controller/resource/monitoring/remotewriteingress/test/externaldns/case-5-cluster-api-v1alpha3.golden
- service/key/key.go
Prometheus remotewrite endpoints for agents: increase max body size from 10m to 50m.
Needed because with latest prometheus-agent tuning of `maxsamplespersend` some clusters get failed sends because they're too big.
I have:
> Prometheus remotewrite endpoints for agents: increase max body size

- CHANGELOG.md
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-4-control-plane.golden
- service/controller/resource/monitoring/verticalpodautoscaler/test/case-5-cluster-api-v1alpha3.golden
Reducing the memory limit to 80% of node size following many incident with node crashes.
I have:
> Set memory limit to 80% of node size

- CHANGELOG.md
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
Prometheus-agent: Revert maxSamplesPerSend to 150000 as we suspect it overloads Prometheis and may be the cause of crashes.
I have:
> Revert maxSamplesPerSend to 150000

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
towards https://github.com/giantswarm/roadmap/issues/2182
In order to have cAdvisor metrics on loki pods, we have to scrape the `loki` namespace.
I have:
> Add loki namespace to cadvisor on MC

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/rbac.yaml
We added finalizers on a PMO secret that we patch out with PMO but PMO is not autorized to patch secret
I have:
> Allow secret patching

- .circleci/config.yml
Shared app collection is deprecated
I have:
> Remove shared app collection

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-cluster-api-v1alpha3.golden
We currently have duplicate targets because the observability bundle app for vintage WC is not where pmo is looking for it
I have:
> Fix Observability Bundle detection for vintage WCs

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
towards https://github.com/giantswarm/giantswarm/issues/26678
To avoid several types of alerts to fire because metrics are missing, we create an inhibition when prometheus-agent is down.
I have:
> Add Inhibition rule when prometheus-agent is down

- CHANGELOG.md
- files/templates/scrapeconfigs/additional-scrape-configs.template.yaml
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-4-control-plane.golden
- service/controller/resource/monitoring/scrapeconfigs/test/kvm/case-4-control-plane.golden
https://gigantic.slack.com/archives/C02HLSDH3DZ/p1682680595002609
I have:
> Keep accepting 'master' as `role` label value for etcd scraping.

- CHANGELOG.md
- service/controller/resource/alerting/heartbeat/resource.go
- service/controller/resource/alerting/heartbeatwebhookconfig/resource.go
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-1-awsconfig.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-2-azureconfig.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-3-kvmconfig.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-4-control-plane.golden
- service/controller/resource/alerting/heartbeatwebhookconfig/test/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/26770
- alertmanager heartbeats config updated for faster response when receiving heartbeats, and less stress on opsgenie
- opsgenie now waits for 1h with no heartbeat before sending an alert, instead of 25min previously
- runbook link style is consistent with other alerts
I have:
> heartbeat tuning

- .nancy-ignore
- CHANGELOG.md
- helm/prometheus-meta-operator/templates/pod-monitor.yaml
- helm/prometheus-meta-operator/templates/rbac.yaml
- pkg/remotewrite/configuration/error.go
- pkg/remotewrite/configuration/type.go
- pkg/remotewrite/configuration/utils.go
- service/controller/managementcluster/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-awsconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-2-azureconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-3-kvmconfig.golden
- service/controller/resource/monitoring/prometheus/test/case-4-control-plane.golden
- service/controller/resource/monitoring/prometheus/test/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/create.go
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/delete.go
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/error.go
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/monitoring/remotewriteconfig/create.go
- service/controller/resource/monitoring/remotewriteconfig/delete.go
- service/controller/resource/monitoring/remotewriteconfig/error.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/remotewriteingressauth/resource.go
- service/controller/resource/monitoring/remotewritesecret/create.go
- service/controller/resource/monitoring/remotewritesecret/delete.go
- service/controller/resource/monitoring/remotewritesecret/error.go
- service/controller/resource/monitoring/remotewritesecret/resource.go
- service/controller/resource/resource.go
- service/key/key.go
Towards https://github.com/giantswarm/roadmap/issues/2419
This PR adds sharding capabilities as well as prometheus-agent version override to this chart.
This PR also splits the current remote write secret into a configmap (remotewriteconfig) containing the prometheus agent configuration (version, external labels, shards) and a secret (remotewritesecret) that contains the remotewriteendpoints. 
This PR also keeps the old way of configuring the agent for older releases
I have:
> Add shard configuration

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/26997
Add alerting pipeline for `team-turtles` slack channels
I have:
> Add team-turtles alerting for slack

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Clippy alert channels have been archived. 
ReRoute the clippy alerts to team-phoenix alert channels 
I have:
> ReRoute clippy alerts to phoenix until all team labels are changed

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Removing unused harbor-implementation channel
I have:
> Remove harbor-implementation integration

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
This change routes only MC alerts to opsgenie when the pipeline is set to stable-testing for the MC.
towards: https://github.com/giantswarm/giantswarm/issues/26718
Related other changes:
- https://github.com/giantswarm/prometheus-rules/pull/825
- https://github.com/giantswarm/installations/pull/2208
- https://github.com/giantswarm/config/pull/1877
I have:
> Stable-testing pipeline only route MC alerts to opsgenie

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
This change ignores WorkloadClusterApps* alerts when the pipeline is set to stable-testing for the MC.
towards: https://github.com/giantswarm/giantswarm/issues/26718
I have:
> Skip workload cluster alerts for stable-pipeline installations.

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/kyverno-policy-exception.yaml
Autogen policies also apply to ReplicaSets, so the current RS would still be blocked.
I have:
> Include ReplicaSet in PolicyException

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-cluster-api-v1alpha3.golden
Towards https://github.com/giantswarm/giantswarm/issues/27693, we have combined with Honeybadger for oncall, so we can now let Shield alerts through to the opsgenie receiver.
I have:
> Enable Shield opsgenie alerts

- CHANGELOG.md
- service/key/key.go
Towards https://github.com/giantswarm/roadmap/issues/2832
On Managed EKS clusters, the api-server URL populated by the CAPA provider starts with `https://` and this causes issue in PMO as it cannot access the following url:
`https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443`
This PR should fix it.
This will be tested on Gauss, Grizzly (CAPA and CAPA EKS) and Snail (Imported EKS)
I have:
> Fix API Server url for Managed EKS

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
This is to support URLs such as `dashboard: https://giantswarm.grafana.net/d/a2f4976Zk/certificates?orgId=1` which do not point to the installation's Grafana, but a Grafana Cloud dashboard. Right now, such URLs get joined to something wrong like `https://installation-grafana/d/https://giantswarm.grafana.net/d/a2f4976Zk/certificates?orgId=1`.
I didn't find a good way of testing this. Should we maybe update `service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case*.golden` with the fixed `{{ define "__dashboardurl" -}}` and add a test in there?
I have:
> Support absolute Grafana dashboard URLs

- CHANGELOG.md
- pkg/prometheusquerier/querier.go
Towards https://github.com/giantswarm/giantswarm/issues/28174
Improve agent shards calculation:
we base our calculations on the max number of series for the last 6 hours, so it changes less often.
I have:
> improve agent shards calculation

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-1-awsconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-2-azureconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-3-kvmconfig.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-4-control-plane.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-5-cluster-api-v1alpha3.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/case-6-cluster-api-eks.golden
Since support for absolute Grafana dashboard URLs (https://github.com/giantswarm/prometheus-meta-operator/pull/1374), alertmanager crashes at startup.
This PR reverts it, so we can take time to properly test and re-introduce this feature later.
I have:
> Revert support absolute Grafana dashboard URLs

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
Grizzly clusters are causing a lot of PMO reconcilation errors because clusters are created a lot and some with issues. Let's not get paged everytime there is an issue on grizzly
I have:
> Ignore PMO reconciliation issues on stable-testing installations

- CHANGELOG.md
- pkg/remotewrite/configuration/utils.go
Towards https://github.com/giantswarm/giantswarm/issues/28239 and https://github.com/giantswarm/giantswarm/issues/27937
We are increasing the number of prometheus-agent max shards from 10 to 50 to avoid issues like:
```
Warning  Unhealthy  34m (x42 over 21h)  kubelet  Liveness probe failed: Desired shards: 24 / max 10
ERROR - watchdog.sh: Overloaded - 24 desired chards for max 10 shards
```
After some testing on anteater/seu01, it at least did not worsen the situation so let's monitor it in real clusters.
I have:
> Increase prometheus-agent max shards

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-ingress.yaml
- helm/prometheus-meta-operator/templates/ingress-oauth.yaml
- helm/prometheus-meta-operator/values.schema.json
- helm/prometheus-meta-operator/values.yaml
This PR introduces a new configuration option to specify the name of the cert-manager ClusterIssuer to be used on Ingress resources installed by the chart in this repository.
Towards https://github.com/giantswarm/roadmap/issues/2844
I have:
> Add ClusterIssuerName configuration option

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-5-eks-v18.golden
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-eks-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-eks-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-5-eks-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-5-eks-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-5-eks-v18.golden
- service/key/key.go
This PR sets the EKS provider when the workload cluster is an EKS cluster towards https://github.com/giantswarm/roadmap/issues/2843
I have:
> Add support for eks as a provider

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
The `ClusterUnhealthyPhase` alert should only page for Workload Clusters that aren't E2E test clusters. The best we have to work this out is the cluster name starting with `t-` as is the convention in the test suites.
I have:
> Route ClusterUnhealthyPhase for test clusters to blackhole

- pkg/cluster/types.go
- pkg/organization/reader.go
- pkg/remotewrite/configuration/utils.go
- service/controller/clusterapi/controller.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanagerconfig/resource.go
- service/controller/resource/alerting/alertmanagerconfig/resource_test.go
- service/controller/resource/certificates/resource.go
- service/controller/resource/etcd-certificates/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/resource_test.go
- service/controller/resource/monitoring/prometheus/test/case-1-vintage-mc.golden
- service/controller/resource/monitoring/prometheus/test/case-2-aws-v16.golden
- service/controller/resource/monitoring/prometheus/test/case-3-aws-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-4-azure-v18.golden
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/remotewriteingressauth/resource.go
- service/controller/resource/monitoring/remotewritesecret/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource_test.go
- service/controller/resource/resource.go
- service/key/key.go
- service/service.go
This PR refactors the provider into a better provider type to be able to use the Flavor field of either CAPI or Vintage.
This will be the basis of other refactorings
As you can see, no golden file was changed for this PR (only the Prometheus one because provider was set to, well, provider)
I have:
> refactor provider into proper type

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-vintage-mc.golden
- service/controller/resource/monitoring/prometheus/test/case-2-aws-v16.golden
- service/controller/resource/monitoring/prometheus/test/case-3-aws-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-4-azure-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-5-eks-v18.golden
Closes https://github.com/giantswarm/giantswarm/issues/28396
This PR sets the seccomp profile for the MC prometheus
I have:
> Add missing seccomp profile to Prometheus

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanagerconfig/resource.go
- service/controller/resource/alerting/alertmanagerconfig/resource_test.go
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-azure-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-eks-v18.golden
Towards https://github.com/giantswarm/giantswarm/issues/28302
This PR ensures the slo alerts are sent to the correct slack channels
To be released after https://github.com/giantswarm/prometheus-rules/pull/925
I have:
> Remove custom SLO handling in alertmanager

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-azure-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-eks-v18.golden
Towards https://github.com/giantswarm/giantswarm/issues/28743
Normally, this should increase the duration before any alert is sent. Let's try this for now
I have:
> increase duration before sending alerts in alertmanager config

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-4-azure-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/case-5-eks-v18.golden
Towards: https://github.com/giantswarm/giantswarm/issues/28751
This PR groups alerts by team in alertmanager so ServiceLevelBurnRateTooHigh alerts are sent to the correct teams
I have:
> group alerts by team

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
Fixes https://github.com/giantswarm/giantswarm/issues/29526
Towards: https://github.com/giantswarm/giantswarm/issues/29553
This PR adds some extra matches to the `stable-testing` blackhole routing so that more alerts related to the test WCs get ignored instead of paging.
I have:
> Improve stable-testing blackhole routing of alerts

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/prometheus/prometheus-cilium-network-policy.yaml
- helm/prometheus-meta-operator/values.schema.json
- helm/prometheus-meta-operator/values.yaml
towards https://github.com/giantswarm/giantswarm/issues/29581
We need to add a netpol to allow managed Prometheuses to talk to the kubernetes API as this is blocked by a deny-all policy.
I have:
> add CiliumNetworkPolicy for managed Prometheuses

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-vintage-mc.golden
- service/controller/resource/monitoring/prometheus/test/case-2-aws-v16.golden
- service/controller/resource/monitoring/prometheus/test/case-3-aws-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-4-azure-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-5-eks-v18.golden
I encountered an error with VPA failing because of this:
```
'Error checking if target is a topmost well-known or scalable controller:                                                                                                                                                      
Unhandled targetRef monitoring.coreos.com/v1 / Prometheus / gaia, last error                                                                                                                                                          
Internal error occurred: the spec replicas field ".spec.shards" does not exist'
```
I'm not exactly sure what causes VPA to complain about that, but it does not hurt to set it explicitly.
I have:
> Always set shards to 1 for all created Prometheuses

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-1-vintage-mc.golden
- service/controller/resource/monitoring/prometheus/test/case-2-aws-v16.golden
- service/controller/resource/monitoring/prometheus/test/case-3-aws-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-4-azure-v18.golden
- service/controller/resource/monitoring/prometheus/test/case-5-eks-v18.golden
We are enabling remote-write-feature in a deprecated way:
`ts=2024-02-05T12:50:23.533Z caller=main.go:172 level=warn msg="Remote write receiver enabled via feature flag remote-write-receiver. This is DEPRECATED. Use --web.enable-remote-write-receiver."`
This PR should fix that
I have:
> Remove deprecated warning

- CHANGELOG.md
- pkg/cluster/types.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/case-5-eks-v18.golden
- service/controller/resource/monitoring/remotewriteapiendpointconfigsecret/resource.go
- service/controller/resource/monitoring/remotewriteconfig/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/scrapeconfigs/test/aws/case-5-eks-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/azure/case-5-eks-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/capa/case-4-azure-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-2-aws-v16.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-3-aws-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/gcp/case-4-azure-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-2-aws-v16.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-3-aws-v18.golden
- service/controller/resource/monitoring/scrapeconfigs/test/openstack/case-4-azure-v18.golden
- service/key/error.go
- service/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/29703
This needs to be tested but this PR adds support for multi-provider MC. It basically configure the provider label depending on the actual infrastructure deployed. We keep it the same for vintage MCs
I have:
> Support multi-provider MCs

- CHANGELOG.md
- service/controller/clusterapi/resource.go
- service/controller/managementcluster/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/resource_test.go
This PR should fix VPA issues that arise with the latest kube-prometheus-stack 9.0.0 release.
The issue are coming from the new `scale` subresource that was added to the prometheus CR so the prometheus operator can scale the number of shards of a Prometheus CR using tools like KEDA or the prometheus adapter.
VPA also relies on the scale subresource to find the resoruces that VPA needs to manage (recommend metrics) and to do that, the vpa controllers go up the  topmost controller that has the scale subresource.
Prior to the upgrade of prometheus operator, the topmost controller was  the statefulsetcontroller, but it is not the Prometheus CR.
TO be able to support slow CAPI upgrades, this PR actually uses the version of the observability bundle that runs on the MC to know if PMO should set …
> Fix VPA for latest prom-operator

- CHANGELOG.md
- service/controller/resource/ciliumnetpol/create.go
This PR aims to fix the current issue with PMO which throws error when a ciliumnetpol already exist for prometheus on the MC. Example log : 
```
{"caller":"github.com/giantswarm/micrologger@v1.1.1/logger.go:88","controller":"prometheus-meta-operator-cluster-api-controller","event":"update","level":"error","loop":"186","message":"retrying due to error","object":"org-adidas/deu01","resource":"ciliumnetpol","stack":{"annotatio
n":"ciliumnetworkpolicies.cilium.io \"deu01-prometheus\" already exists","kind":"unknown","stack":[{"file":"/root/project/service/controller/resource/ciliumnetpol/create.go","line":31},{"file":"/go/pkg/mod/github.com/giantswarm/operatorkit/v7@v7.2.0/pkg/resource/wrapper/retryresour
ce/basic_resource.go","line":52}]},"time":"2024-02-12T14:59:38.510872+00:00","version":"1 …
```
> add logging to debug issue with already existing cilium netpols

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager/cilium-network-policy.yaml
Alertmanager is failing to work on gcapeverde, because it's lacking a CNP
I have:
> Add alertmanager missing CNP

- CHANGELOG.md
- go.mod
- service/controller/clusterapi/resource.go
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanagerwiring/resource.go
- service/controller/resource/alerting/alertmanagerwiring/resource_test.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/monitoring/prometheus/test/mimir-enabled/vintage/case-4-azure-v18.golden
- service/controller/resource/noop/noop.go
Towards https://github.com/giantswarm/roadmap/issues/3160
This PR removes alerting from prometheus to alertmanager if mimir is enabled to avoid duplicate alerts.
Alerting will keep working thanks to https://github.com/giantswarm/shared-configs/commit/bcd2f81fe326c06d7cd3f076006e3d642d866fa6
I have:
> Remove alerting from Prometheus if mimir is enabled

- CHANGELOG.md
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager.yaml
Towards https://github.com/giantswarm/wepa/issues/62
I have:
> Remove alertmanager namespace injection in matchers

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/30612
Ensure when a Proxy URL is configured it is also set within the http_config for slack.
> fix slack_configs http_config missing proxy_url

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
Towards: https://github.com/giantswarm/giantswarm/issues/26508
Removes "apiserver_down" dummy inhibition, substituted by "cluster_control_plane_unhealthy". 
I have:
> Replace apiserver down with controlplane unhealthy

- CHANGELOG.md
- service/controller/clusterapi/resource.go
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/heartbeat/create.go
- service/controller/resource/alerting/heartbeat/resource.go
- service/controller/resource/alerting/heartbeatwebhookconfig/resource.go
Towards https://github.com/giantswarm/roadmap/issues/3218 this PR gets rids of olds heartbeats when Mimir is enabled
I have:
> Mimir enabled: Delete per cluster heartbeats

- CHANGELOG.md
- service/controller/resource/generic/create.go
- service/controller/resource/generic/resource.go
This PR replaces all the generic resource removal PRs to make sure we can delete resources when moving to Mimir
I have:
> add-delete-if-mimir-enabled to generic resource

- CHANGELOG.md
- service/controller/clusterapi/resource.go
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanagerwiring/resource.go
- service/controller/resource/certificates/create.go
- service/controller/resource/certificates/delete.go
- service/controller/resource/certificates/resource.go
- service/controller/resource/ciliumnetpol/create.go
- service/controller/resource/ciliumnetpol/delete.go
- service/controller/resource/ciliumnetpol/resource.go
- service/controller/resource/etcd-certificates/resource.go
- service/controller/resource/monitoring/ingress/resource.go
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/remotewriteingress/create.go
- service/controller/resource/monitoring/remotewriteingress/resource.go
- service/controller/resource/monitoring/remotewriteingressauth/create.go
- service/controller/resource/monitoring/remotewriteingressauth/resource.go
- service/controller/resource/monitoring/scrapeconfigs/resource.go
- service/controller/resource/monitoring/verticalpodautoscaler/create.go
- service/controller/resource/monitoring/verticalpodautoscaler/delete.go
- service/controller/resource/monitoring/verticalpodautoscaler/resource.go
- service/controller/resource/namespace/resource.go
- service/controller/resource/rbac/create.go
- service/controller/resource/rbac/delete.go
- service/controller/resource/rbac/resource.go
Towards https://github.com/giantswarm/roadmap/issues/3218
This PR always delete resources when mimir is enabled so we do not have leftovers
I have:
> Remove resources when mimir is enabled

- CHANGELOG.md
- pkg/remotewriteutils/util.go
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
This PR fixes the tests that have been broken since the last PR and also ignores the prometheus-to-grafana-cloud exporter from the list of managed prometheus so PMO does not remove the remote write section of the prometheus-to-grafana-cloud exporter
Before:
```sh
k get prometheus -A --selector 'app.kubernetes.io/name notin (prometheus-agent)'
NAMESPACE                         NAME                     VERSION   DESIRED   READY   RECONCILED   AVAILABLE   AGE
gaggle-prometheus                 gaggle                   v2.50.1   1         1       True         True        77d
mimir                             mimir-to-grafana-cloud   v2.50.1   1         1       True         True        18h
t-9ac4ne83nii993f55r-prometheus   t-9ac4ne83nii993f55r     v2.50.1   1         1       True         True …
```
> ignore prometheus buddy in the remote-write-controller

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
This PR fixes the slack links as slack is sensitive to line breaks
Before:
After:
I have:
> fix-slack-notification-links 

- CHANGELOG.md
- flag/service/alertmanager/alertmanager.go
- flag/service/service.go
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-global-secret.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-ingress.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-psp.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-rbac.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-service-account.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager-tls-secret.yaml
- helm/prometheus-meta-operator/templates/alertmanager/alertmanager.yaml
- helm/prometheus-meta-operator/templates/alertmanager/cilium-network-policy.yaml
- helm/prometheus-meta-operator/templates/alertmanager/servicemonitor.yaml
- helm/prometheus-meta-operator/templates/configmap.yaml
- helm/prometheus-meta-operator/templates/prometheus/prometheus-psp.yaml
- helm/prometheus-meta-operator/templates/prometheus/prometheus-rbac.yaml
- helm/prometheus-meta-operator/values.yaml
- main.go
- service/controller/managementcluster/controller.go
- service/controller/managementcluster/resource.go
- service/controller/resource/alerting/alertmanagerconfig/create.go
- service/controller/resource/alerting/alertmanagerconfig/resource.go
- service/service.go
Towards https://github.com/giantswarm/roadmap/issues/3513
Add support to disable alertmanager if monitoring is disabled at the installation level 
I have:
> support disabling alertmanager and its resources on mimir backed installations

- CHANGELOG.md
- service/controller/managementcluster/resource.go
Current AlertManager configuration on Vintage is broken.
I have:
> Fix AlertManager configuration generation on Vintage

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
Towards https://github.com/giantswarm/roadmap/issues/3590.
We now use alloy as a monitoring agent so having the inhibition named prometheus-agent makes no sense. 
This PR renames both inbititions about missing prometheus agent to monitoring agent.
I have:
> rename prometheus-agent inbitions to monitoring agent to be able to take alloy into account

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
This PR gets rid of the old prometheus-agent inhibitions as they were replaced by monitoring-agent inhibitions https://github.com/giantswarm/prometheus-meta-operator/pull/1753 and used in alerts https://github.com/giantswarm/prometheus-rules/pull/1405 and sloth alerts https://github.com/giantswarm/sloth-rules/pull/253 which were both released :)
I have:
> remove useless prometheus-agent inhibitions as they were replaced

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
This PR introduces the following changes into the Alertmanager notification template:
- Update alert and query URLs for Mimir to point to the Active notification rather than the rule page
- Move link section (runbook, dashboard, explors) before instance to avoid them being lost due to OpsGenie max description being reached
- Move the warnings for missing runbook and dashboard up into the link section
> Update Alertmanager notification template

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
Remove the Alertmanager link in Alerts and replace it with the silences repository in order to provide a more meaningful place for users to go to when they want to manage silences.
Also improved the Silences repository readme there https://github.com/giantswarm/silences/pull/1898
> Replace Alertmanager link with Silence repository in Alerts notifications

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
Replacing the silence link also on Slack, and points it to the Silences repository.
> Replace silence link with silence repo, also on Slack

- CHANGELOG.md
- go.mod
- go.sum
```
go get -u golang.org/x/net
go: upgraded golang.org/x/net v0.32.0 => v0.33.0
```
> Fix CVE-2024-45338 by updating golang.org/x/net to v0.33.0

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
Use the `proxy_from_environment` option in the Alertmanager configuration to make it read the proxy settings from environment variables (HTTP_PROXY, HTTPS_PROXY, NO_PROXY, etc...) rather having the operator setting proxy via `proxy_url`.
See https://prometheus.io/docs/alerting/0.26/configuration/#http_config
2 things are happening here:
- Replace `proxy_url` in favor of `proxy_from_environment`
- Move the `SlackApiToken` condition so `proxy_from_environment` is not dependent on it
> Use proxy_from_environment in Alertmanager

- CHANGELOG.md
- files/templates/alertmanager/notification-template.tmpl
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/notification-template/mimir-enabled/vintage/case-3-aws-v18.golden
The new link is misleading as user lands on a page where they should be able to explore data using the `see source` link in Grafana, but this leads to a page not found.
This PR restores the previous link for Alerts. We can revisit this in the future when we have Mimir Alertmanager.
> Fix restore previous Alerts link and fix see source link

- CHANGELOG.md
- files/templates/alertmanager/alertmanager.yaml
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/classic/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/mimir-enabled/vintage/case-3-aws-v18.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-1-capa-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-2-capa.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-3-capz.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-4-eks.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/capi/case-5-gcp.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-1-vintage-mc.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-2-aws-v16.golden
- service/controller/resource/alerting/alertmanagerconfig/test/alertmanager-config/slack-token/vintage/case-3-aws-v18.golden
This reverts commit 3f42eba776926ba4c89b19312c3b59b733f25731.
This is because `proxy_from_environment` breaks in most of our installations currently, as its only supported from observability-bundle >= 1.8
- https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.77.0
- https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-65.1.1/charts/kube-prometheus-stack/Chart.yaml#L27
- https://github.com/giantswarm/kube-prometheus-stack-app/blob/v12.0.0/helm/kube-prometheus-stack/Chart.yaml#L16
- https://github.com/giantswarm/observability-bundle/blob/v1.8.0/helm/observability-bundle/values.yaml#L111
> Revert "Use proxy_from_environment in Alertmanager (#1782)"

- CHANGELOG.md
- service/controller/resource/monitoring/prometheus/resource.go
- service/controller/resource/monitoring/prometheus/test/classic/capi/case-1-capa-mc.golden
- service/controller/resource/monitoring/prometheus/test/classic/capi/case-2-capa.golden
- service/controller/resource/monitoring/prometheus/test/classic/capi/case-3-capz.golden
- service/controller/resource/monitoring/prometheus/test/classic/capi/case-4-eks.golden
- service/controller/resource/monitoring/prometheus/test/classic/capi/case-5-gcp.golden
- service/controller/resource/monitoring/prometheus/test/classic/vintage/case-1-vintage-mc.golden
- service/controller/resource/monitoring/prometheus/test/classic/vintage/case-2-aws-v16.golden
- service/controller/resource/monitoring/prometheus/test/classic/vintage/case-3-aws-v18.golden
Towards https://github.com/giantswarm/roadmap/issues/3678
Without this, prometheus operator on vintage installation tries to load loki rules into prometheus and this might create some alerts.
This makes sure we do not load loki rules in vintage Prometheus
I have:
> do not load log based alerts
